// Code generated by go-swagger; DO NOT EDIT.

package issue_template_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/piper-validation/fortify-client-go/models"
)

// DeleteIssueTemplateReader is a Reader for the DeleteIssueTemplate structure.
type DeleteIssueTemplateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteIssueTemplateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteIssueTemplateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteIssueTemplateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteIssueTemplateUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteIssueTemplateForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteIssueTemplateNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewDeleteIssueTemplateConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteIssueTemplateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteIssueTemplateOK creates a DeleteIssueTemplateOK with default headers values
func NewDeleteIssueTemplateOK() *DeleteIssueTemplateOK {
	return &DeleteIssueTemplateOK{}
}

/*DeleteIssueTemplateOK handles this case with default header values.

OK
*/
type DeleteIssueTemplateOK struct {
	Payload *models.APIResultVoid
}

func (o *DeleteIssueTemplateOK) Error() string {
	return fmt.Sprintf("[DELETE /issueTemplates/{id}][%d] deleteIssueTemplateOK  %+v", 200, o.Payload)
}

func (o *DeleteIssueTemplateOK) GetPayload() *models.APIResultVoid {
	return o.Payload
}

func (o *DeleteIssueTemplateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResultVoid)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteIssueTemplateBadRequest creates a DeleteIssueTemplateBadRequest with default headers values
func NewDeleteIssueTemplateBadRequest() *DeleteIssueTemplateBadRequest {
	return &DeleteIssueTemplateBadRequest{}
}

/*DeleteIssueTemplateBadRequest handles this case with default header values.

Bad Request
*/
type DeleteIssueTemplateBadRequest struct {
	Payload *models.APIResult
}

func (o *DeleteIssueTemplateBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /issueTemplates/{id}][%d] deleteIssueTemplateBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteIssueTemplateBadRequest) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *DeleteIssueTemplateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteIssueTemplateUnauthorized creates a DeleteIssueTemplateUnauthorized with default headers values
func NewDeleteIssueTemplateUnauthorized() *DeleteIssueTemplateUnauthorized {
	return &DeleteIssueTemplateUnauthorized{}
}

/*DeleteIssueTemplateUnauthorized handles this case with default header values.

Unauthorized
*/
type DeleteIssueTemplateUnauthorized struct {
	Payload *models.APIResult
}

func (o *DeleteIssueTemplateUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /issueTemplates/{id}][%d] deleteIssueTemplateUnauthorized  %+v", 401, o.Payload)
}

func (o *DeleteIssueTemplateUnauthorized) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *DeleteIssueTemplateUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteIssueTemplateForbidden creates a DeleteIssueTemplateForbidden with default headers values
func NewDeleteIssueTemplateForbidden() *DeleteIssueTemplateForbidden {
	return &DeleteIssueTemplateForbidden{}
}

/*DeleteIssueTemplateForbidden handles this case with default header values.

Forbidden
*/
type DeleteIssueTemplateForbidden struct {
	Payload *models.APIResult
}

func (o *DeleteIssueTemplateForbidden) Error() string {
	return fmt.Sprintf("[DELETE /issueTemplates/{id}][%d] deleteIssueTemplateForbidden  %+v", 403, o.Payload)
}

func (o *DeleteIssueTemplateForbidden) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *DeleteIssueTemplateForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteIssueTemplateNotFound creates a DeleteIssueTemplateNotFound with default headers values
func NewDeleteIssueTemplateNotFound() *DeleteIssueTemplateNotFound {
	return &DeleteIssueTemplateNotFound{}
}

/*DeleteIssueTemplateNotFound handles this case with default header values.

Not Found
*/
type DeleteIssueTemplateNotFound struct {
	Payload *models.APIResult
}

func (o *DeleteIssueTemplateNotFound) Error() string {
	return fmt.Sprintf("[DELETE /issueTemplates/{id}][%d] deleteIssueTemplateNotFound  %+v", 404, o.Payload)
}

func (o *DeleteIssueTemplateNotFound) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *DeleteIssueTemplateNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteIssueTemplateConflict creates a DeleteIssueTemplateConflict with default headers values
func NewDeleteIssueTemplateConflict() *DeleteIssueTemplateConflict {
	return &DeleteIssueTemplateConflict{}
}

/*DeleteIssueTemplateConflict handles this case with default header values.

Conflict
*/
type DeleteIssueTemplateConflict struct {
	Payload *models.APIResult
}

func (o *DeleteIssueTemplateConflict) Error() string {
	return fmt.Sprintf("[DELETE /issueTemplates/{id}][%d] deleteIssueTemplateConflict  %+v", 409, o.Payload)
}

func (o *DeleteIssueTemplateConflict) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *DeleteIssueTemplateConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteIssueTemplateInternalServerError creates a DeleteIssueTemplateInternalServerError with default headers values
func NewDeleteIssueTemplateInternalServerError() *DeleteIssueTemplateInternalServerError {
	return &DeleteIssueTemplateInternalServerError{}
}

/*DeleteIssueTemplateInternalServerError handles this case with default header values.

Internal Server Error
*/
type DeleteIssueTemplateInternalServerError struct {
	Payload *models.APIResult
}

func (o *DeleteIssueTemplateInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /issueTemplates/{id}][%d] deleteIssueTemplateInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteIssueTemplateInternalServerError) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *DeleteIssueTemplateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
