// Code generated by go-swagger; DO NOT EDIT.

package custom_tag_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/piper-validation/fortify-client-go/models"
)

// CreateCustomTagReader is a Reader for the CreateCustomTag structure.
type CreateCustomTagReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateCustomTagReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateCustomTagCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateCustomTagBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCreateCustomTagUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateCustomTagForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCreateCustomTagNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewCreateCustomTagConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateCustomTagInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateCustomTagCreated creates a CreateCustomTagCreated with default headers values
func NewCreateCustomTagCreated() *CreateCustomTagCreated {
	return &CreateCustomTagCreated{}
}

/*CreateCustomTagCreated handles this case with default header values.

Created
*/
type CreateCustomTagCreated struct {
	Payload *models.APIResultCustomTag
}

func (o *CreateCustomTagCreated) Error() string {
	return fmt.Sprintf("[POST /customTags][%d] createCustomTagCreated  %+v", 201, o.Payload)
}

func (o *CreateCustomTagCreated) GetPayload() *models.APIResultCustomTag {
	return o.Payload
}

func (o *CreateCustomTagCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResultCustomTag)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateCustomTagBadRequest creates a CreateCustomTagBadRequest with default headers values
func NewCreateCustomTagBadRequest() *CreateCustomTagBadRequest {
	return &CreateCustomTagBadRequest{}
}

/*CreateCustomTagBadRequest handles this case with default header values.

Bad Request
*/
type CreateCustomTagBadRequest struct {
	Payload *models.APIResult
}

func (o *CreateCustomTagBadRequest) Error() string {
	return fmt.Sprintf("[POST /customTags][%d] createCustomTagBadRequest  %+v", 400, o.Payload)
}

func (o *CreateCustomTagBadRequest) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *CreateCustomTagBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateCustomTagUnauthorized creates a CreateCustomTagUnauthorized with default headers values
func NewCreateCustomTagUnauthorized() *CreateCustomTagUnauthorized {
	return &CreateCustomTagUnauthorized{}
}

/*CreateCustomTagUnauthorized handles this case with default header values.

Unauthorized
*/
type CreateCustomTagUnauthorized struct {
	Payload *models.APIResult
}

func (o *CreateCustomTagUnauthorized) Error() string {
	return fmt.Sprintf("[POST /customTags][%d] createCustomTagUnauthorized  %+v", 401, o.Payload)
}

func (o *CreateCustomTagUnauthorized) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *CreateCustomTagUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateCustomTagForbidden creates a CreateCustomTagForbidden with default headers values
func NewCreateCustomTagForbidden() *CreateCustomTagForbidden {
	return &CreateCustomTagForbidden{}
}

/*CreateCustomTagForbidden handles this case with default header values.

Forbidden
*/
type CreateCustomTagForbidden struct {
	Payload *models.APIResult
}

func (o *CreateCustomTagForbidden) Error() string {
	return fmt.Sprintf("[POST /customTags][%d] createCustomTagForbidden  %+v", 403, o.Payload)
}

func (o *CreateCustomTagForbidden) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *CreateCustomTagForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateCustomTagNotFound creates a CreateCustomTagNotFound with default headers values
func NewCreateCustomTagNotFound() *CreateCustomTagNotFound {
	return &CreateCustomTagNotFound{}
}

/*CreateCustomTagNotFound handles this case with default header values.

Not Found
*/
type CreateCustomTagNotFound struct {
	Payload *models.APIResult
}

func (o *CreateCustomTagNotFound) Error() string {
	return fmt.Sprintf("[POST /customTags][%d] createCustomTagNotFound  %+v", 404, o.Payload)
}

func (o *CreateCustomTagNotFound) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *CreateCustomTagNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateCustomTagConflict creates a CreateCustomTagConflict with default headers values
func NewCreateCustomTagConflict() *CreateCustomTagConflict {
	return &CreateCustomTagConflict{}
}

/*CreateCustomTagConflict handles this case with default header values.

Conflict
*/
type CreateCustomTagConflict struct {
	Payload *models.APIResult
}

func (o *CreateCustomTagConflict) Error() string {
	return fmt.Sprintf("[POST /customTags][%d] createCustomTagConflict  %+v", 409, o.Payload)
}

func (o *CreateCustomTagConflict) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *CreateCustomTagConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateCustomTagInternalServerError creates a CreateCustomTagInternalServerError with default headers values
func NewCreateCustomTagInternalServerError() *CreateCustomTagInternalServerError {
	return &CreateCustomTagInternalServerError{}
}

/*CreateCustomTagInternalServerError handles this case with default header values.

Internal Server Error
*/
type CreateCustomTagInternalServerError struct {
	Payload *models.APIResult
}

func (o *CreateCustomTagInternalServerError) Error() string {
	return fmt.Sprintf("[POST /customTags][%d] createCustomTagInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateCustomTagInternalServerError) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *CreateCustomTagInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
