// Code generated by go-swagger; DO NOT EDIT.

package system_configuration_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/piper-validation/fortify-client-go/models"
)

// ReadSystemConfigurationReader is a Reader for the ReadSystemConfiguration structure.
type ReadSystemConfigurationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReadSystemConfigurationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewReadSystemConfigurationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewReadSystemConfigurationBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewReadSystemConfigurationUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewReadSystemConfigurationForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewReadSystemConfigurationNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewReadSystemConfigurationConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewReadSystemConfigurationInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewReadSystemConfigurationOK creates a ReadSystemConfigurationOK with default headers values
func NewReadSystemConfigurationOK() *ReadSystemConfigurationOK {
	return &ReadSystemConfigurationOK{}
}

/*ReadSystemConfigurationOK handles this case with default header values.

OK
*/
type ReadSystemConfigurationOK struct {
	Payload *models.APIResultSystemConfiguration
}

func (o *ReadSystemConfigurationOK) Error() string {
	return fmt.Sprintf("[GET /systemConfiguration/{name}][%d] readSystemConfigurationOK  %+v", 200, o.Payload)
}

func (o *ReadSystemConfigurationOK) GetPayload() *models.APIResultSystemConfiguration {
	return o.Payload
}

func (o *ReadSystemConfigurationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResultSystemConfiguration)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewReadSystemConfigurationBadRequest creates a ReadSystemConfigurationBadRequest with default headers values
func NewReadSystemConfigurationBadRequest() *ReadSystemConfigurationBadRequest {
	return &ReadSystemConfigurationBadRequest{}
}

/*ReadSystemConfigurationBadRequest handles this case with default header values.

Bad Request
*/
type ReadSystemConfigurationBadRequest struct {
	Payload *models.APIResult
}

func (o *ReadSystemConfigurationBadRequest) Error() string {
	return fmt.Sprintf("[GET /systemConfiguration/{name}][%d] readSystemConfigurationBadRequest  %+v", 400, o.Payload)
}

func (o *ReadSystemConfigurationBadRequest) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *ReadSystemConfigurationBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewReadSystemConfigurationUnauthorized creates a ReadSystemConfigurationUnauthorized with default headers values
func NewReadSystemConfigurationUnauthorized() *ReadSystemConfigurationUnauthorized {
	return &ReadSystemConfigurationUnauthorized{}
}

/*ReadSystemConfigurationUnauthorized handles this case with default header values.

Unauthorized
*/
type ReadSystemConfigurationUnauthorized struct {
	Payload *models.APIResult
}

func (o *ReadSystemConfigurationUnauthorized) Error() string {
	return fmt.Sprintf("[GET /systemConfiguration/{name}][%d] readSystemConfigurationUnauthorized  %+v", 401, o.Payload)
}

func (o *ReadSystemConfigurationUnauthorized) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *ReadSystemConfigurationUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewReadSystemConfigurationForbidden creates a ReadSystemConfigurationForbidden with default headers values
func NewReadSystemConfigurationForbidden() *ReadSystemConfigurationForbidden {
	return &ReadSystemConfigurationForbidden{}
}

/*ReadSystemConfigurationForbidden handles this case with default header values.

Forbidden
*/
type ReadSystemConfigurationForbidden struct {
	Payload *models.APIResult
}

func (o *ReadSystemConfigurationForbidden) Error() string {
	return fmt.Sprintf("[GET /systemConfiguration/{name}][%d] readSystemConfigurationForbidden  %+v", 403, o.Payload)
}

func (o *ReadSystemConfigurationForbidden) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *ReadSystemConfigurationForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewReadSystemConfigurationNotFound creates a ReadSystemConfigurationNotFound with default headers values
func NewReadSystemConfigurationNotFound() *ReadSystemConfigurationNotFound {
	return &ReadSystemConfigurationNotFound{}
}

/*ReadSystemConfigurationNotFound handles this case with default header values.

Not Found
*/
type ReadSystemConfigurationNotFound struct {
	Payload *models.APIResult
}

func (o *ReadSystemConfigurationNotFound) Error() string {
	return fmt.Sprintf("[GET /systemConfiguration/{name}][%d] readSystemConfigurationNotFound  %+v", 404, o.Payload)
}

func (o *ReadSystemConfigurationNotFound) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *ReadSystemConfigurationNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewReadSystemConfigurationConflict creates a ReadSystemConfigurationConflict with default headers values
func NewReadSystemConfigurationConflict() *ReadSystemConfigurationConflict {
	return &ReadSystemConfigurationConflict{}
}

/*ReadSystemConfigurationConflict handles this case with default header values.

Conflict
*/
type ReadSystemConfigurationConflict struct {
	Payload *models.APIResult
}

func (o *ReadSystemConfigurationConflict) Error() string {
	return fmt.Sprintf("[GET /systemConfiguration/{name}][%d] readSystemConfigurationConflict  %+v", 409, o.Payload)
}

func (o *ReadSystemConfigurationConflict) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *ReadSystemConfigurationConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewReadSystemConfigurationInternalServerError creates a ReadSystemConfigurationInternalServerError with default headers values
func NewReadSystemConfigurationInternalServerError() *ReadSystemConfigurationInternalServerError {
	return &ReadSystemConfigurationInternalServerError{}
}

/*ReadSystemConfigurationInternalServerError handles this case with default header values.

Internal Server Error
*/
type ReadSystemConfigurationInternalServerError struct {
	Payload *models.APIResult
}

func (o *ReadSystemConfigurationInternalServerError) Error() string {
	return fmt.Sprintf("[GET /systemConfiguration/{name}][%d] readSystemConfigurationInternalServerError  %+v", 500, o.Payload)
}

func (o *ReadSystemConfigurationInternalServerError) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *ReadSystemConfigurationInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
