// Code generated by go-swagger; DO NOT EDIT.

package cloud_pool_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListCloudPoolParams creates a new ListCloudPoolParams object
// with the default values initialized.
func NewListCloudPoolParams() *ListCloudPoolParams {
	var (
		fulltextsearchDefault = bool(false)
		limitDefault          = int32(200)
		startDefault          = int32(0)
	)
	return &ListCloudPoolParams{
		Fulltextsearch: &fulltextsearchDefault,
		Limit:          &limitDefault,
		Start:          &startDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewListCloudPoolParamsWithTimeout creates a new ListCloudPoolParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListCloudPoolParamsWithTimeout(timeout time.Duration) *ListCloudPoolParams {
	var (
		fulltextsearchDefault = bool(false)
		limitDefault          = int32(200)
		startDefault          = int32(0)
	)
	return &ListCloudPoolParams{
		Fulltextsearch: &fulltextsearchDefault,
		Limit:          &limitDefault,
		Start:          &startDefault,

		timeout: timeout,
	}
}

// NewListCloudPoolParamsWithContext creates a new ListCloudPoolParams object
// with the default values initialized, and the ability to set a context for a request
func NewListCloudPoolParamsWithContext(ctx context.Context) *ListCloudPoolParams {
	var (
		fulltextsearchDefault = bool(false)
		limitDefault          = int32(200)
		startDefault          = int32(0)
	)
	return &ListCloudPoolParams{
		Fulltextsearch: &fulltextsearchDefault,
		Limit:          &limitDefault,
		Start:          &startDefault,

		Context: ctx,
	}
}

// NewListCloudPoolParamsWithHTTPClient creates a new ListCloudPoolParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListCloudPoolParamsWithHTTPClient(client *http.Client) *ListCloudPoolParams {
	var (
		fulltextsearchDefault = bool(false)
		limitDefault          = int32(200)
		startDefault          = int32(0)
	)
	return &ListCloudPoolParams{
		Fulltextsearch: &fulltextsearchDefault,
		Limit:          &limitDefault,
		Start:          &startDefault,
		HTTPClient:     client,
	}
}

/*ListCloudPoolParams contains all the parameters to send to the API endpoint
for the list cloud pool operation typically these are written to a http.Request
*/
type ListCloudPoolParams struct {

	/*Fields
	  Output fields

	*/
	Fields *string
	/*Fulltextsearch
	  If 'true', interpret 'q' parameter as full text search query, defaults to 'false'

	*/
	Fulltextsearch *bool
	/*Limit
	  A maximum number of returned objects in listing, if '-1' or '0' no limit is applied

	*/
	Limit *int32
	/*Orderby
	  Fields to order by

	*/
	Orderby *string
	/*Q
	  A search-spec of full text search query (see fulltextsearch parameter)

	*/
	Q *string
	/*Start
	  A start offset in object listing

	*/
	Start *int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list cloud pool params
func (o *ListCloudPoolParams) WithTimeout(timeout time.Duration) *ListCloudPoolParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list cloud pool params
func (o *ListCloudPoolParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list cloud pool params
func (o *ListCloudPoolParams) WithContext(ctx context.Context) *ListCloudPoolParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list cloud pool params
func (o *ListCloudPoolParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list cloud pool params
func (o *ListCloudPoolParams) WithHTTPClient(client *http.Client) *ListCloudPoolParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list cloud pool params
func (o *ListCloudPoolParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFields adds the fields to the list cloud pool params
func (o *ListCloudPoolParams) WithFields(fields *string) *ListCloudPoolParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the list cloud pool params
func (o *ListCloudPoolParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithFulltextsearch adds the fulltextsearch to the list cloud pool params
func (o *ListCloudPoolParams) WithFulltextsearch(fulltextsearch *bool) *ListCloudPoolParams {
	o.SetFulltextsearch(fulltextsearch)
	return o
}

// SetFulltextsearch adds the fulltextsearch to the list cloud pool params
func (o *ListCloudPoolParams) SetFulltextsearch(fulltextsearch *bool) {
	o.Fulltextsearch = fulltextsearch
}

// WithLimit adds the limit to the list cloud pool params
func (o *ListCloudPoolParams) WithLimit(limit *int32) *ListCloudPoolParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the list cloud pool params
func (o *ListCloudPoolParams) SetLimit(limit *int32) {
	o.Limit = limit
}

// WithOrderby adds the orderby to the list cloud pool params
func (o *ListCloudPoolParams) WithOrderby(orderby *string) *ListCloudPoolParams {
	o.SetOrderby(orderby)
	return o
}

// SetOrderby adds the orderby to the list cloud pool params
func (o *ListCloudPoolParams) SetOrderby(orderby *string) {
	o.Orderby = orderby
}

// WithQ adds the q to the list cloud pool params
func (o *ListCloudPoolParams) WithQ(q *string) *ListCloudPoolParams {
	o.SetQ(q)
	return o
}

// SetQ adds the q to the list cloud pool params
func (o *ListCloudPoolParams) SetQ(q *string) {
	o.Q = q
}

// WithStart adds the start to the list cloud pool params
func (o *ListCloudPoolParams) WithStart(start *int32) *ListCloudPoolParams {
	o.SetStart(start)
	return o
}

// SetStart adds the start to the list cloud pool params
func (o *ListCloudPoolParams) SetStart(start *int32) {
	o.Start = start
}

// WriteToRequest writes these params to a swagger request
func (o *ListCloudPoolParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	if o.Fulltextsearch != nil {

		// query param fulltextsearch
		var qrFulltextsearch bool
		if o.Fulltextsearch != nil {
			qrFulltextsearch = *o.Fulltextsearch
		}
		qFulltextsearch := swag.FormatBool(qrFulltextsearch)
		if qFulltextsearch != "" {
			if err := r.SetQueryParam("fulltextsearch", qFulltextsearch); err != nil {
				return err
			}
		}

	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int32
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt32(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Orderby != nil {

		// query param orderby
		var qrOrderby string
		if o.Orderby != nil {
			qrOrderby = *o.Orderby
		}
		qOrderby := qrOrderby
		if qOrderby != "" {
			if err := r.SetQueryParam("orderby", qOrderby); err != nil {
				return err
			}
		}

	}

	if o.Q != nil {

		// query param q
		var qrQ string
		if o.Q != nil {
			qrQ = *o.Q
		}
		qQ := qrQ
		if qQ != "" {
			if err := r.SetQueryParam("q", qQ); err != nil {
				return err
			}
		}

	}

	if o.Start != nil {

		// query param start
		var qrStart int32
		if o.Start != nil {
			qrStart = *o.Start
		}
		qStart := swag.FormatInt32(qrStart)
		if qStart != "" {
			if err := r.SetQueryParam("start", qStart); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
