// Code generated by go-swagger; DO NOT EDIT.

package report_definition_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/piper-validation/fortify-client-go/models"
)

// MultiDeleteReportDefinitionReader is a Reader for the MultiDeleteReportDefinition structure.
type MultiDeleteReportDefinitionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MultiDeleteReportDefinitionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewMultiDeleteReportDefinitionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewMultiDeleteReportDefinitionBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewMultiDeleteReportDefinitionUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewMultiDeleteReportDefinitionForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewMultiDeleteReportDefinitionNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewMultiDeleteReportDefinitionConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewMultiDeleteReportDefinitionInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewMultiDeleteReportDefinitionOK creates a MultiDeleteReportDefinitionOK with default headers values
func NewMultiDeleteReportDefinitionOK() *MultiDeleteReportDefinitionOK {
	return &MultiDeleteReportDefinitionOK{}
}

/*MultiDeleteReportDefinitionOK handles this case with default header values.

OK
*/
type MultiDeleteReportDefinitionOK struct {
	Payload *models.APIResultVoid
}

func (o *MultiDeleteReportDefinitionOK) Error() string {
	return fmt.Sprintf("[DELETE /reportDefinitions][%d] multiDeleteReportDefinitionOK  %+v", 200, o.Payload)
}

func (o *MultiDeleteReportDefinitionOK) GetPayload() *models.APIResultVoid {
	return o.Payload
}

func (o *MultiDeleteReportDefinitionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResultVoid)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMultiDeleteReportDefinitionBadRequest creates a MultiDeleteReportDefinitionBadRequest with default headers values
func NewMultiDeleteReportDefinitionBadRequest() *MultiDeleteReportDefinitionBadRequest {
	return &MultiDeleteReportDefinitionBadRequest{}
}

/*MultiDeleteReportDefinitionBadRequest handles this case with default header values.

Bad Request
*/
type MultiDeleteReportDefinitionBadRequest struct {
	Payload *models.APIResult
}

func (o *MultiDeleteReportDefinitionBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /reportDefinitions][%d] multiDeleteReportDefinitionBadRequest  %+v", 400, o.Payload)
}

func (o *MultiDeleteReportDefinitionBadRequest) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *MultiDeleteReportDefinitionBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMultiDeleteReportDefinitionUnauthorized creates a MultiDeleteReportDefinitionUnauthorized with default headers values
func NewMultiDeleteReportDefinitionUnauthorized() *MultiDeleteReportDefinitionUnauthorized {
	return &MultiDeleteReportDefinitionUnauthorized{}
}

/*MultiDeleteReportDefinitionUnauthorized handles this case with default header values.

Unauthorized
*/
type MultiDeleteReportDefinitionUnauthorized struct {
	Payload *models.APIResult
}

func (o *MultiDeleteReportDefinitionUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /reportDefinitions][%d] multiDeleteReportDefinitionUnauthorized  %+v", 401, o.Payload)
}

func (o *MultiDeleteReportDefinitionUnauthorized) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *MultiDeleteReportDefinitionUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMultiDeleteReportDefinitionForbidden creates a MultiDeleteReportDefinitionForbidden with default headers values
func NewMultiDeleteReportDefinitionForbidden() *MultiDeleteReportDefinitionForbidden {
	return &MultiDeleteReportDefinitionForbidden{}
}

/*MultiDeleteReportDefinitionForbidden handles this case with default header values.

Forbidden
*/
type MultiDeleteReportDefinitionForbidden struct {
	Payload *models.APIResult
}

func (o *MultiDeleteReportDefinitionForbidden) Error() string {
	return fmt.Sprintf("[DELETE /reportDefinitions][%d] multiDeleteReportDefinitionForbidden  %+v", 403, o.Payload)
}

func (o *MultiDeleteReportDefinitionForbidden) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *MultiDeleteReportDefinitionForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMultiDeleteReportDefinitionNotFound creates a MultiDeleteReportDefinitionNotFound with default headers values
func NewMultiDeleteReportDefinitionNotFound() *MultiDeleteReportDefinitionNotFound {
	return &MultiDeleteReportDefinitionNotFound{}
}

/*MultiDeleteReportDefinitionNotFound handles this case with default header values.

Not Found
*/
type MultiDeleteReportDefinitionNotFound struct {
	Payload *models.APIResult
}

func (o *MultiDeleteReportDefinitionNotFound) Error() string {
	return fmt.Sprintf("[DELETE /reportDefinitions][%d] multiDeleteReportDefinitionNotFound  %+v", 404, o.Payload)
}

func (o *MultiDeleteReportDefinitionNotFound) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *MultiDeleteReportDefinitionNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMultiDeleteReportDefinitionConflict creates a MultiDeleteReportDefinitionConflict with default headers values
func NewMultiDeleteReportDefinitionConflict() *MultiDeleteReportDefinitionConflict {
	return &MultiDeleteReportDefinitionConflict{}
}

/*MultiDeleteReportDefinitionConflict handles this case with default header values.

Conflict
*/
type MultiDeleteReportDefinitionConflict struct {
	Payload *models.APIResult
}

func (o *MultiDeleteReportDefinitionConflict) Error() string {
	return fmt.Sprintf("[DELETE /reportDefinitions][%d] multiDeleteReportDefinitionConflict  %+v", 409, o.Payload)
}

func (o *MultiDeleteReportDefinitionConflict) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *MultiDeleteReportDefinitionConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMultiDeleteReportDefinitionInternalServerError creates a MultiDeleteReportDefinitionInternalServerError with default headers values
func NewMultiDeleteReportDefinitionInternalServerError() *MultiDeleteReportDefinitionInternalServerError {
	return &MultiDeleteReportDefinitionInternalServerError{}
}

/*MultiDeleteReportDefinitionInternalServerError handles this case with default header values.

Internal Server Error
*/
type MultiDeleteReportDefinitionInternalServerError struct {
	Payload *models.APIResult
}

func (o *MultiDeleteReportDefinitionInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /reportDefinitions][%d] multiDeleteReportDefinitionInternalServerError  %+v", 500, o.Payload)
}

func (o *MultiDeleteReportDefinitionInternalServerError) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *MultiDeleteReportDefinitionInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
