// Code generated by go-swagger; DO NOT EDIT.

package report_definition_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewMultiDeleteReportDefinitionParams creates a new MultiDeleteReportDefinitionParams object
// with the default values initialized.
func NewMultiDeleteReportDefinitionParams() *MultiDeleteReportDefinitionParams {
	var ()
	return &MultiDeleteReportDefinitionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewMultiDeleteReportDefinitionParamsWithTimeout creates a new MultiDeleteReportDefinitionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewMultiDeleteReportDefinitionParamsWithTimeout(timeout time.Duration) *MultiDeleteReportDefinitionParams {
	var ()
	return &MultiDeleteReportDefinitionParams{

		timeout: timeout,
	}
}

// NewMultiDeleteReportDefinitionParamsWithContext creates a new MultiDeleteReportDefinitionParams object
// with the default values initialized, and the ability to set a context for a request
func NewMultiDeleteReportDefinitionParamsWithContext(ctx context.Context) *MultiDeleteReportDefinitionParams {
	var ()
	return &MultiDeleteReportDefinitionParams{

		Context: ctx,
	}
}

// NewMultiDeleteReportDefinitionParamsWithHTTPClient creates a new MultiDeleteReportDefinitionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewMultiDeleteReportDefinitionParamsWithHTTPClient(client *http.Client) *MultiDeleteReportDefinitionParams {
	var ()
	return &MultiDeleteReportDefinitionParams{
		HTTPClient: client,
	}
}

/*MultiDeleteReportDefinitionParams contains all the parameters to send to the API endpoint
for the multi delete report definition operation typically these are written to a http.Request
*/
type MultiDeleteReportDefinitionParams struct {

	/*Ids
	  A comma-separated list of resource identifiers

	*/
	Ids string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the multi delete report definition params
func (o *MultiDeleteReportDefinitionParams) WithTimeout(timeout time.Duration) *MultiDeleteReportDefinitionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the multi delete report definition params
func (o *MultiDeleteReportDefinitionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the multi delete report definition params
func (o *MultiDeleteReportDefinitionParams) WithContext(ctx context.Context) *MultiDeleteReportDefinitionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the multi delete report definition params
func (o *MultiDeleteReportDefinitionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the multi delete report definition params
func (o *MultiDeleteReportDefinitionParams) WithHTTPClient(client *http.Client) *MultiDeleteReportDefinitionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the multi delete report definition params
func (o *MultiDeleteReportDefinitionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIds adds the ids to the multi delete report definition params
func (o *MultiDeleteReportDefinitionParams) WithIds(ids string) *MultiDeleteReportDefinitionParams {
	o.SetIds(ids)
	return o
}

// SetIds adds the ids to the multi delete report definition params
func (o *MultiDeleteReportDefinitionParams) SetIds(ids string) {
	o.Ids = ids
}

// WriteToRequest writes these params to a swagger request
func (o *MultiDeleteReportDefinitionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param ids
	qrIds := o.Ids
	qIds := qrIds
	if qIds != "" {
		if err := r.SetQueryParam("ids", qIds); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
