// Code generated by go-swagger; DO NOT EDIT.

package bug_tracker_of_project_version_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/piper-validation/fortify-client-go/models"
)

// NewUpdateCollectionBugTrackerOfProjectVersionParams creates a new UpdateCollectionBugTrackerOfProjectVersionParams object
// with the default values initialized.
func NewUpdateCollectionBugTrackerOfProjectVersionParams() *UpdateCollectionBugTrackerOfProjectVersionParams {
	var ()
	return &UpdateCollectionBugTrackerOfProjectVersionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateCollectionBugTrackerOfProjectVersionParamsWithTimeout creates a new UpdateCollectionBugTrackerOfProjectVersionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateCollectionBugTrackerOfProjectVersionParamsWithTimeout(timeout time.Duration) *UpdateCollectionBugTrackerOfProjectVersionParams {
	var ()
	return &UpdateCollectionBugTrackerOfProjectVersionParams{

		timeout: timeout,
	}
}

// NewUpdateCollectionBugTrackerOfProjectVersionParamsWithContext creates a new UpdateCollectionBugTrackerOfProjectVersionParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateCollectionBugTrackerOfProjectVersionParamsWithContext(ctx context.Context) *UpdateCollectionBugTrackerOfProjectVersionParams {
	var ()
	return &UpdateCollectionBugTrackerOfProjectVersionParams{

		Context: ctx,
	}
}

// NewUpdateCollectionBugTrackerOfProjectVersionParamsWithHTTPClient creates a new UpdateCollectionBugTrackerOfProjectVersionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateCollectionBugTrackerOfProjectVersionParamsWithHTTPClient(client *http.Client) *UpdateCollectionBugTrackerOfProjectVersionParams {
	var ()
	return &UpdateCollectionBugTrackerOfProjectVersionParams{
		HTTPClient: client,
	}
}

/*UpdateCollectionBugTrackerOfProjectVersionParams contains all the parameters to send to the API endpoint
for the update collection bug tracker of project version operation typically these are written to a http.Request
*/
type UpdateCollectionBugTrackerOfProjectVersionParams struct {

	/*Data
	  data

	*/
	Data []*models.ProjectVersionBugTracker
	/*ParentID
	  parentId

	*/
	ParentID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update collection bug tracker of project version params
func (o *UpdateCollectionBugTrackerOfProjectVersionParams) WithTimeout(timeout time.Duration) *UpdateCollectionBugTrackerOfProjectVersionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update collection bug tracker of project version params
func (o *UpdateCollectionBugTrackerOfProjectVersionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update collection bug tracker of project version params
func (o *UpdateCollectionBugTrackerOfProjectVersionParams) WithContext(ctx context.Context) *UpdateCollectionBugTrackerOfProjectVersionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update collection bug tracker of project version params
func (o *UpdateCollectionBugTrackerOfProjectVersionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update collection bug tracker of project version params
func (o *UpdateCollectionBugTrackerOfProjectVersionParams) WithHTTPClient(client *http.Client) *UpdateCollectionBugTrackerOfProjectVersionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update collection bug tracker of project version params
func (o *UpdateCollectionBugTrackerOfProjectVersionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the update collection bug tracker of project version params
func (o *UpdateCollectionBugTrackerOfProjectVersionParams) WithData(data []*models.ProjectVersionBugTracker) *UpdateCollectionBugTrackerOfProjectVersionParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the update collection bug tracker of project version params
func (o *UpdateCollectionBugTrackerOfProjectVersionParams) SetData(data []*models.ProjectVersionBugTracker) {
	o.Data = data
}

// WithParentID adds the parentID to the update collection bug tracker of project version params
func (o *UpdateCollectionBugTrackerOfProjectVersionParams) WithParentID(parentID int64) *UpdateCollectionBugTrackerOfProjectVersionParams {
	o.SetParentID(parentID)
	return o
}

// SetParentID adds the parentId to the update collection bug tracker of project version params
func (o *UpdateCollectionBugTrackerOfProjectVersionParams) SetParentID(parentID int64) {
	o.ParentID = parentID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateCollectionBugTrackerOfProjectVersionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	// path param parentId
	if err := r.SetPathParam("parentId", swag.FormatInt64(o.ParentID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
