// Code generated by go-swagger; DO NOT EDIT.

package job_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/piper-validation/fortify-client-go/models"
)

// NewCancelJobParams creates a new CancelJobParams object
// with the default values initialized.
func NewCancelJobParams() *CancelJobParams {
	var ()
	return &CancelJobParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCancelJobParamsWithTimeout creates a new CancelJobParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCancelJobParamsWithTimeout(timeout time.Duration) *CancelJobParams {
	var ()
	return &CancelJobParams{

		timeout: timeout,
	}
}

// NewCancelJobParamsWithContext creates a new CancelJobParams object
// with the default values initialized, and the ability to set a context for a request
func NewCancelJobParamsWithContext(ctx context.Context) *CancelJobParams {
	var ()
	return &CancelJobParams{

		Context: ctx,
	}
}

// NewCancelJobParamsWithHTTPClient creates a new CancelJobParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCancelJobParamsWithHTTPClient(client *http.Client) *CancelJobParams {
	var ()
	return &CancelJobParams{
		HTTPClient: client,
	}
}

/*CancelJobParams contains all the parameters to send to the API endpoint
for the cancel job operation typically these are written to a http.Request
*/
type CancelJobParams struct {

	/*Resource
	  resource

	*/
	Resource *models.JobCancelRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the cancel job params
func (o *CancelJobParams) WithTimeout(timeout time.Duration) *CancelJobParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the cancel job params
func (o *CancelJobParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the cancel job params
func (o *CancelJobParams) WithContext(ctx context.Context) *CancelJobParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the cancel job params
func (o *CancelJobParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the cancel job params
func (o *CancelJobParams) WithHTTPClient(client *http.Client) *CancelJobParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the cancel job params
func (o *CancelJobParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithResource adds the resource to the cancel job params
func (o *CancelJobParams) WithResource(resource *models.JobCancelRequest) *CancelJobParams {
	o.SetResource(resource)
	return o
}

// SetResource adds the resource to the cancel job params
func (o *CancelJobParams) SetResource(resource *models.JobCancelRequest) {
	o.Resource = resource
}

// WriteToRequest writes these params to a swagger request
func (o *CancelJobParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Resource != nil {
		if err := r.SetBodyParam(o.Resource); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
