// Code generated by go-swagger; DO NOT EDIT.

package job_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/piper-validation/fortify-client-go/models"
)

// CancelJobReader is a Reader for the CancelJob structure.
type CancelJobReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CancelJobReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCancelJobOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCancelJobBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCancelJobUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCancelJobForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCancelJobNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewCancelJobConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCancelJobInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCancelJobOK creates a CancelJobOK with default headers values
func NewCancelJobOK() *CancelJobOK {
	return &CancelJobOK{}
}

/*CancelJobOK handles this case with default header values.

OK
*/
type CancelJobOK struct {
	Payload *models.APIResultVoid
}

func (o *CancelJobOK) Error() string {
	return fmt.Sprintf("[POST /jobs/action/cancel][%d] cancelJobOK  %+v", 200, o.Payload)
}

func (o *CancelJobOK) GetPayload() *models.APIResultVoid {
	return o.Payload
}

func (o *CancelJobOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResultVoid)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCancelJobBadRequest creates a CancelJobBadRequest with default headers values
func NewCancelJobBadRequest() *CancelJobBadRequest {
	return &CancelJobBadRequest{}
}

/*CancelJobBadRequest handles this case with default header values.

Bad Request
*/
type CancelJobBadRequest struct {
	Payload *models.APIResult
}

func (o *CancelJobBadRequest) Error() string {
	return fmt.Sprintf("[POST /jobs/action/cancel][%d] cancelJobBadRequest  %+v", 400, o.Payload)
}

func (o *CancelJobBadRequest) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *CancelJobBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCancelJobUnauthorized creates a CancelJobUnauthorized with default headers values
func NewCancelJobUnauthorized() *CancelJobUnauthorized {
	return &CancelJobUnauthorized{}
}

/*CancelJobUnauthorized handles this case with default header values.

Unauthorized
*/
type CancelJobUnauthorized struct {
	Payload *models.APIResult
}

func (o *CancelJobUnauthorized) Error() string {
	return fmt.Sprintf("[POST /jobs/action/cancel][%d] cancelJobUnauthorized  %+v", 401, o.Payload)
}

func (o *CancelJobUnauthorized) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *CancelJobUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCancelJobForbidden creates a CancelJobForbidden with default headers values
func NewCancelJobForbidden() *CancelJobForbidden {
	return &CancelJobForbidden{}
}

/*CancelJobForbidden handles this case with default header values.

Forbidden
*/
type CancelJobForbidden struct {
	Payload *models.APIResult
}

func (o *CancelJobForbidden) Error() string {
	return fmt.Sprintf("[POST /jobs/action/cancel][%d] cancelJobForbidden  %+v", 403, o.Payload)
}

func (o *CancelJobForbidden) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *CancelJobForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCancelJobNotFound creates a CancelJobNotFound with default headers values
func NewCancelJobNotFound() *CancelJobNotFound {
	return &CancelJobNotFound{}
}

/*CancelJobNotFound handles this case with default header values.

Not Found
*/
type CancelJobNotFound struct {
	Payload *models.APIResult
}

func (o *CancelJobNotFound) Error() string {
	return fmt.Sprintf("[POST /jobs/action/cancel][%d] cancelJobNotFound  %+v", 404, o.Payload)
}

func (o *CancelJobNotFound) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *CancelJobNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCancelJobConflict creates a CancelJobConflict with default headers values
func NewCancelJobConflict() *CancelJobConflict {
	return &CancelJobConflict{}
}

/*CancelJobConflict handles this case with default header values.

Conflict
*/
type CancelJobConflict struct {
	Payload *models.APIResult
}

func (o *CancelJobConflict) Error() string {
	return fmt.Sprintf("[POST /jobs/action/cancel][%d] cancelJobConflict  %+v", 409, o.Payload)
}

func (o *CancelJobConflict) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *CancelJobConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCancelJobInternalServerError creates a CancelJobInternalServerError with default headers values
func NewCancelJobInternalServerError() *CancelJobInternalServerError {
	return &CancelJobInternalServerError{}
}

/*CancelJobInternalServerError handles this case with default header values.

Internal Server Error
*/
type CancelJobInternalServerError struct {
	Payload *models.APIResult
}

func (o *CancelJobInternalServerError) Error() string {
	return fmt.Sprintf("[POST /jobs/action/cancel][%d] cancelJobInternalServerError  %+v", 500, o.Payload)
}

func (o *CancelJobInternalServerError) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *CancelJobInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
