// Code generated by go-swagger; DO NOT EDIT.

package custom_tag_of_project_version_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListCustomTagOfProjectVersionParams creates a new ListCustomTagOfProjectVersionParams object
// with the default values initialized.
func NewListCustomTagOfProjectVersionParams() *ListCustomTagOfProjectVersionParams {
	var (
		includeallDefault = bool(false)
		limitDefault      = int32(200)
		startDefault      = int32(0)
	)
	return &ListCustomTagOfProjectVersionParams{
		Includeall: &includeallDefault,
		Limit:      &limitDefault,
		Start:      &startDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewListCustomTagOfProjectVersionParamsWithTimeout creates a new ListCustomTagOfProjectVersionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListCustomTagOfProjectVersionParamsWithTimeout(timeout time.Duration) *ListCustomTagOfProjectVersionParams {
	var (
		includeallDefault = bool(false)
		limitDefault      = int32(200)
		startDefault      = int32(0)
	)
	return &ListCustomTagOfProjectVersionParams{
		Includeall: &includeallDefault,
		Limit:      &limitDefault,
		Start:      &startDefault,

		timeout: timeout,
	}
}

// NewListCustomTagOfProjectVersionParamsWithContext creates a new ListCustomTagOfProjectVersionParams object
// with the default values initialized, and the ability to set a context for a request
func NewListCustomTagOfProjectVersionParamsWithContext(ctx context.Context) *ListCustomTagOfProjectVersionParams {
	var (
		includeallDefault = bool(false)
		limitDefault      = int32(200)
		startDefault      = int32(0)
	)
	return &ListCustomTagOfProjectVersionParams{
		Includeall: &includeallDefault,
		Limit:      &limitDefault,
		Start:      &startDefault,

		Context: ctx,
	}
}

// NewListCustomTagOfProjectVersionParamsWithHTTPClient creates a new ListCustomTagOfProjectVersionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListCustomTagOfProjectVersionParamsWithHTTPClient(client *http.Client) *ListCustomTagOfProjectVersionParams {
	var (
		includeallDefault = bool(false)
		limitDefault      = int32(200)
		startDefault      = int32(0)
	)
	return &ListCustomTagOfProjectVersionParams{
		Includeall: &includeallDefault,
		Limit:      &limitDefault,
		Start:      &startDefault,
		HTTPClient: client,
	}
}

/*ListCustomTagOfProjectVersionParams contains all the parameters to send to the API endpoint
for the list custom tag of project version operation typically these are written to a http.Request
*/
type ListCustomTagOfProjectVersionParams struct {

	/*Fields
	  Output fields

	*/
	Fields *string
	/*Includeall
	  includeall

	*/
	Includeall *bool
	/*Limit
	  A maximum number of returned objects in listing, if '-1' or '0' no limit is applied

	*/
	Limit *int32
	/*Orderby
	  Fields to order by

	*/
	Orderby *string
	/*ParentID
	  parentId

	*/
	ParentID int64
	/*Q
	  A search query

	*/
	Q *string
	/*Start
	  A start offset in object listing

	*/
	Start *int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list custom tag of project version params
func (o *ListCustomTagOfProjectVersionParams) WithTimeout(timeout time.Duration) *ListCustomTagOfProjectVersionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list custom tag of project version params
func (o *ListCustomTagOfProjectVersionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list custom tag of project version params
func (o *ListCustomTagOfProjectVersionParams) WithContext(ctx context.Context) *ListCustomTagOfProjectVersionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list custom tag of project version params
func (o *ListCustomTagOfProjectVersionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list custom tag of project version params
func (o *ListCustomTagOfProjectVersionParams) WithHTTPClient(client *http.Client) *ListCustomTagOfProjectVersionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list custom tag of project version params
func (o *ListCustomTagOfProjectVersionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFields adds the fields to the list custom tag of project version params
func (o *ListCustomTagOfProjectVersionParams) WithFields(fields *string) *ListCustomTagOfProjectVersionParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the list custom tag of project version params
func (o *ListCustomTagOfProjectVersionParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithIncludeall adds the includeall to the list custom tag of project version params
func (o *ListCustomTagOfProjectVersionParams) WithIncludeall(includeall *bool) *ListCustomTagOfProjectVersionParams {
	o.SetIncludeall(includeall)
	return o
}

// SetIncludeall adds the includeall to the list custom tag of project version params
func (o *ListCustomTagOfProjectVersionParams) SetIncludeall(includeall *bool) {
	o.Includeall = includeall
}

// WithLimit adds the limit to the list custom tag of project version params
func (o *ListCustomTagOfProjectVersionParams) WithLimit(limit *int32) *ListCustomTagOfProjectVersionParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the list custom tag of project version params
func (o *ListCustomTagOfProjectVersionParams) SetLimit(limit *int32) {
	o.Limit = limit
}

// WithOrderby adds the orderby to the list custom tag of project version params
func (o *ListCustomTagOfProjectVersionParams) WithOrderby(orderby *string) *ListCustomTagOfProjectVersionParams {
	o.SetOrderby(orderby)
	return o
}

// SetOrderby adds the orderby to the list custom tag of project version params
func (o *ListCustomTagOfProjectVersionParams) SetOrderby(orderby *string) {
	o.Orderby = orderby
}

// WithParentID adds the parentID to the list custom tag of project version params
func (o *ListCustomTagOfProjectVersionParams) WithParentID(parentID int64) *ListCustomTagOfProjectVersionParams {
	o.SetParentID(parentID)
	return o
}

// SetParentID adds the parentId to the list custom tag of project version params
func (o *ListCustomTagOfProjectVersionParams) SetParentID(parentID int64) {
	o.ParentID = parentID
}

// WithQ adds the q to the list custom tag of project version params
func (o *ListCustomTagOfProjectVersionParams) WithQ(q *string) *ListCustomTagOfProjectVersionParams {
	o.SetQ(q)
	return o
}

// SetQ adds the q to the list custom tag of project version params
func (o *ListCustomTagOfProjectVersionParams) SetQ(q *string) {
	o.Q = q
}

// WithStart adds the start to the list custom tag of project version params
func (o *ListCustomTagOfProjectVersionParams) WithStart(start *int32) *ListCustomTagOfProjectVersionParams {
	o.SetStart(start)
	return o
}

// SetStart adds the start to the list custom tag of project version params
func (o *ListCustomTagOfProjectVersionParams) SetStart(start *int32) {
	o.Start = start
}

// WriteToRequest writes these params to a swagger request
func (o *ListCustomTagOfProjectVersionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	if o.Includeall != nil {

		// query param includeall
		var qrIncludeall bool
		if o.Includeall != nil {
			qrIncludeall = *o.Includeall
		}
		qIncludeall := swag.FormatBool(qrIncludeall)
		if qIncludeall != "" {
			if err := r.SetQueryParam("includeall", qIncludeall); err != nil {
				return err
			}
		}

	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int32
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt32(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Orderby != nil {

		// query param orderby
		var qrOrderby string
		if o.Orderby != nil {
			qrOrderby = *o.Orderby
		}
		qOrderby := qrOrderby
		if qOrderby != "" {
			if err := r.SetQueryParam("orderby", qOrderby); err != nil {
				return err
			}
		}

	}

	// path param parentId
	if err := r.SetPathParam("parentId", swag.FormatInt64(o.ParentID)); err != nil {
		return err
	}

	if o.Q != nil {

		// query param q
		var qrQ string
		if o.Q != nil {
			qrQ = *o.Q
		}
		qQ := qrQ
		if qQ != "" {
			if err := r.SetQueryParam("q", qQ); err != nil {
				return err
			}
		}

	}

	if o.Start != nil {

		// query param start
		var qrStart int32
		if o.Start != nil {
			qrStart = *o.Start
		}
		qStart := swag.FormatInt32(qrStart)
		if qStart != "" {
			if err := r.SetQueryParam("start", qStart); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
