// Code generated by go-swagger; DO NOT EDIT.

package custom_tag_of_project_version_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/piper-validation/fortify-client-go/models"
)

// UpdateCollectionCustomTagOfProjectVersionReader is a Reader for the UpdateCollectionCustomTagOfProjectVersion structure.
type UpdateCollectionCustomTagOfProjectVersionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateCollectionCustomTagOfProjectVersionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateCollectionCustomTagOfProjectVersionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateCollectionCustomTagOfProjectVersionBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewUpdateCollectionCustomTagOfProjectVersionUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewUpdateCollectionCustomTagOfProjectVersionForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUpdateCollectionCustomTagOfProjectVersionNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewUpdateCollectionCustomTagOfProjectVersionConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewUpdateCollectionCustomTagOfProjectVersionInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateCollectionCustomTagOfProjectVersionOK creates a UpdateCollectionCustomTagOfProjectVersionOK with default headers values
func NewUpdateCollectionCustomTagOfProjectVersionOK() *UpdateCollectionCustomTagOfProjectVersionOK {
	return &UpdateCollectionCustomTagOfProjectVersionOK{}
}

/*UpdateCollectionCustomTagOfProjectVersionOK handles this case with default header values.

OK
*/
type UpdateCollectionCustomTagOfProjectVersionOK struct {
	Payload *models.APIResultListCustomTag
}

func (o *UpdateCollectionCustomTagOfProjectVersionOK) Error() string {
	return fmt.Sprintf("[PUT /projectVersions/{parentId}/customTags][%d] updateCollectionCustomTagOfProjectVersionOK  %+v", 200, o.Payload)
}

func (o *UpdateCollectionCustomTagOfProjectVersionOK) GetPayload() *models.APIResultListCustomTag {
	return o.Payload
}

func (o *UpdateCollectionCustomTagOfProjectVersionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResultListCustomTag)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateCollectionCustomTagOfProjectVersionBadRequest creates a UpdateCollectionCustomTagOfProjectVersionBadRequest with default headers values
func NewUpdateCollectionCustomTagOfProjectVersionBadRequest() *UpdateCollectionCustomTagOfProjectVersionBadRequest {
	return &UpdateCollectionCustomTagOfProjectVersionBadRequest{}
}

/*UpdateCollectionCustomTagOfProjectVersionBadRequest handles this case with default header values.

Bad Request
*/
type UpdateCollectionCustomTagOfProjectVersionBadRequest struct {
	Payload *models.APIResult
}

func (o *UpdateCollectionCustomTagOfProjectVersionBadRequest) Error() string {
	return fmt.Sprintf("[PUT /projectVersions/{parentId}/customTags][%d] updateCollectionCustomTagOfProjectVersionBadRequest  %+v", 400, o.Payload)
}

func (o *UpdateCollectionCustomTagOfProjectVersionBadRequest) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *UpdateCollectionCustomTagOfProjectVersionBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateCollectionCustomTagOfProjectVersionUnauthorized creates a UpdateCollectionCustomTagOfProjectVersionUnauthorized with default headers values
func NewUpdateCollectionCustomTagOfProjectVersionUnauthorized() *UpdateCollectionCustomTagOfProjectVersionUnauthorized {
	return &UpdateCollectionCustomTagOfProjectVersionUnauthorized{}
}

/*UpdateCollectionCustomTagOfProjectVersionUnauthorized handles this case with default header values.

Unauthorized
*/
type UpdateCollectionCustomTagOfProjectVersionUnauthorized struct {
	Payload *models.APIResult
}

func (o *UpdateCollectionCustomTagOfProjectVersionUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /projectVersions/{parentId}/customTags][%d] updateCollectionCustomTagOfProjectVersionUnauthorized  %+v", 401, o.Payload)
}

func (o *UpdateCollectionCustomTagOfProjectVersionUnauthorized) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *UpdateCollectionCustomTagOfProjectVersionUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateCollectionCustomTagOfProjectVersionForbidden creates a UpdateCollectionCustomTagOfProjectVersionForbidden with default headers values
func NewUpdateCollectionCustomTagOfProjectVersionForbidden() *UpdateCollectionCustomTagOfProjectVersionForbidden {
	return &UpdateCollectionCustomTagOfProjectVersionForbidden{}
}

/*UpdateCollectionCustomTagOfProjectVersionForbidden handles this case with default header values.

Forbidden
*/
type UpdateCollectionCustomTagOfProjectVersionForbidden struct {
	Payload *models.APIResult
}

func (o *UpdateCollectionCustomTagOfProjectVersionForbidden) Error() string {
	return fmt.Sprintf("[PUT /projectVersions/{parentId}/customTags][%d] updateCollectionCustomTagOfProjectVersionForbidden  %+v", 403, o.Payload)
}

func (o *UpdateCollectionCustomTagOfProjectVersionForbidden) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *UpdateCollectionCustomTagOfProjectVersionForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateCollectionCustomTagOfProjectVersionNotFound creates a UpdateCollectionCustomTagOfProjectVersionNotFound with default headers values
func NewUpdateCollectionCustomTagOfProjectVersionNotFound() *UpdateCollectionCustomTagOfProjectVersionNotFound {
	return &UpdateCollectionCustomTagOfProjectVersionNotFound{}
}

/*UpdateCollectionCustomTagOfProjectVersionNotFound handles this case with default header values.

Not Found
*/
type UpdateCollectionCustomTagOfProjectVersionNotFound struct {
	Payload *models.APIResult
}

func (o *UpdateCollectionCustomTagOfProjectVersionNotFound) Error() string {
	return fmt.Sprintf("[PUT /projectVersions/{parentId}/customTags][%d] updateCollectionCustomTagOfProjectVersionNotFound  %+v", 404, o.Payload)
}

func (o *UpdateCollectionCustomTagOfProjectVersionNotFound) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *UpdateCollectionCustomTagOfProjectVersionNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateCollectionCustomTagOfProjectVersionConflict creates a UpdateCollectionCustomTagOfProjectVersionConflict with default headers values
func NewUpdateCollectionCustomTagOfProjectVersionConflict() *UpdateCollectionCustomTagOfProjectVersionConflict {
	return &UpdateCollectionCustomTagOfProjectVersionConflict{}
}

/*UpdateCollectionCustomTagOfProjectVersionConflict handles this case with default header values.

Conflict
*/
type UpdateCollectionCustomTagOfProjectVersionConflict struct {
	Payload *models.APIResult
}

func (o *UpdateCollectionCustomTagOfProjectVersionConflict) Error() string {
	return fmt.Sprintf("[PUT /projectVersions/{parentId}/customTags][%d] updateCollectionCustomTagOfProjectVersionConflict  %+v", 409, o.Payload)
}

func (o *UpdateCollectionCustomTagOfProjectVersionConflict) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *UpdateCollectionCustomTagOfProjectVersionConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateCollectionCustomTagOfProjectVersionInternalServerError creates a UpdateCollectionCustomTagOfProjectVersionInternalServerError with default headers values
func NewUpdateCollectionCustomTagOfProjectVersionInternalServerError() *UpdateCollectionCustomTagOfProjectVersionInternalServerError {
	return &UpdateCollectionCustomTagOfProjectVersionInternalServerError{}
}

/*UpdateCollectionCustomTagOfProjectVersionInternalServerError handles this case with default header values.

Internal Server Error
*/
type UpdateCollectionCustomTagOfProjectVersionInternalServerError struct {
	Payload *models.APIResult
}

func (o *UpdateCollectionCustomTagOfProjectVersionInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /projectVersions/{parentId}/customTags][%d] updateCollectionCustomTagOfProjectVersionInternalServerError  %+v", 500, o.Payload)
}

func (o *UpdateCollectionCustomTagOfProjectVersionInternalServerError) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *UpdateCollectionCustomTagOfProjectVersionInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
