// Code generated by go-swagger; DO NOT EDIT.

package performance_indicator_history_of_project_version_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/piper-validation/fortify-client-go/models"
)

// ListPerformanceIndicatorHistoryOfProjectVersionReader is a Reader for the ListPerformanceIndicatorHistoryOfProjectVersion structure.
type ListPerformanceIndicatorHistoryOfProjectVersionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListPerformanceIndicatorHistoryOfProjectVersionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListPerformanceIndicatorHistoryOfProjectVersionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListPerformanceIndicatorHistoryOfProjectVersionBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewListPerformanceIndicatorHistoryOfProjectVersionUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewListPerformanceIndicatorHistoryOfProjectVersionForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewListPerformanceIndicatorHistoryOfProjectVersionNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewListPerformanceIndicatorHistoryOfProjectVersionConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewListPerformanceIndicatorHistoryOfProjectVersionInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListPerformanceIndicatorHistoryOfProjectVersionOK creates a ListPerformanceIndicatorHistoryOfProjectVersionOK with default headers values
func NewListPerformanceIndicatorHistoryOfProjectVersionOK() *ListPerformanceIndicatorHistoryOfProjectVersionOK {
	return &ListPerformanceIndicatorHistoryOfProjectVersionOK{}
}

/*ListPerformanceIndicatorHistoryOfProjectVersionOK handles this case with default header values.

OK
*/
type ListPerformanceIndicatorHistoryOfProjectVersionOK struct {
	Payload *models.APIResultListPerformanceIndicatorHistory
}

func (o *ListPerformanceIndicatorHistoryOfProjectVersionOK) Error() string {
	return fmt.Sprintf("[GET /projectVersions/{parentId}/performanceIndicatorHistories][%d] listPerformanceIndicatorHistoryOfProjectVersionOK  %+v", 200, o.Payload)
}

func (o *ListPerformanceIndicatorHistoryOfProjectVersionOK) GetPayload() *models.APIResultListPerformanceIndicatorHistory {
	return o.Payload
}

func (o *ListPerformanceIndicatorHistoryOfProjectVersionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResultListPerformanceIndicatorHistory)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListPerformanceIndicatorHistoryOfProjectVersionBadRequest creates a ListPerformanceIndicatorHistoryOfProjectVersionBadRequest with default headers values
func NewListPerformanceIndicatorHistoryOfProjectVersionBadRequest() *ListPerformanceIndicatorHistoryOfProjectVersionBadRequest {
	return &ListPerformanceIndicatorHistoryOfProjectVersionBadRequest{}
}

/*ListPerformanceIndicatorHistoryOfProjectVersionBadRequest handles this case with default header values.

Bad Request
*/
type ListPerformanceIndicatorHistoryOfProjectVersionBadRequest struct {
	Payload *models.APIResult
}

func (o *ListPerformanceIndicatorHistoryOfProjectVersionBadRequest) Error() string {
	return fmt.Sprintf("[GET /projectVersions/{parentId}/performanceIndicatorHistories][%d] listPerformanceIndicatorHistoryOfProjectVersionBadRequest  %+v", 400, o.Payload)
}

func (o *ListPerformanceIndicatorHistoryOfProjectVersionBadRequest) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *ListPerformanceIndicatorHistoryOfProjectVersionBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListPerformanceIndicatorHistoryOfProjectVersionUnauthorized creates a ListPerformanceIndicatorHistoryOfProjectVersionUnauthorized with default headers values
func NewListPerformanceIndicatorHistoryOfProjectVersionUnauthorized() *ListPerformanceIndicatorHistoryOfProjectVersionUnauthorized {
	return &ListPerformanceIndicatorHistoryOfProjectVersionUnauthorized{}
}

/*ListPerformanceIndicatorHistoryOfProjectVersionUnauthorized handles this case with default header values.

Unauthorized
*/
type ListPerformanceIndicatorHistoryOfProjectVersionUnauthorized struct {
	Payload *models.APIResult
}

func (o *ListPerformanceIndicatorHistoryOfProjectVersionUnauthorized) Error() string {
	return fmt.Sprintf("[GET /projectVersions/{parentId}/performanceIndicatorHistories][%d] listPerformanceIndicatorHistoryOfProjectVersionUnauthorized  %+v", 401, o.Payload)
}

func (o *ListPerformanceIndicatorHistoryOfProjectVersionUnauthorized) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *ListPerformanceIndicatorHistoryOfProjectVersionUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListPerformanceIndicatorHistoryOfProjectVersionForbidden creates a ListPerformanceIndicatorHistoryOfProjectVersionForbidden with default headers values
func NewListPerformanceIndicatorHistoryOfProjectVersionForbidden() *ListPerformanceIndicatorHistoryOfProjectVersionForbidden {
	return &ListPerformanceIndicatorHistoryOfProjectVersionForbidden{}
}

/*ListPerformanceIndicatorHistoryOfProjectVersionForbidden handles this case with default header values.

Forbidden
*/
type ListPerformanceIndicatorHistoryOfProjectVersionForbidden struct {
	Payload *models.APIResult
}

func (o *ListPerformanceIndicatorHistoryOfProjectVersionForbidden) Error() string {
	return fmt.Sprintf("[GET /projectVersions/{parentId}/performanceIndicatorHistories][%d] listPerformanceIndicatorHistoryOfProjectVersionForbidden  %+v", 403, o.Payload)
}

func (o *ListPerformanceIndicatorHistoryOfProjectVersionForbidden) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *ListPerformanceIndicatorHistoryOfProjectVersionForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListPerformanceIndicatorHistoryOfProjectVersionNotFound creates a ListPerformanceIndicatorHistoryOfProjectVersionNotFound with default headers values
func NewListPerformanceIndicatorHistoryOfProjectVersionNotFound() *ListPerformanceIndicatorHistoryOfProjectVersionNotFound {
	return &ListPerformanceIndicatorHistoryOfProjectVersionNotFound{}
}

/*ListPerformanceIndicatorHistoryOfProjectVersionNotFound handles this case with default header values.

Not Found
*/
type ListPerformanceIndicatorHistoryOfProjectVersionNotFound struct {
	Payload *models.APIResult
}

func (o *ListPerformanceIndicatorHistoryOfProjectVersionNotFound) Error() string {
	return fmt.Sprintf("[GET /projectVersions/{parentId}/performanceIndicatorHistories][%d] listPerformanceIndicatorHistoryOfProjectVersionNotFound  %+v", 404, o.Payload)
}

func (o *ListPerformanceIndicatorHistoryOfProjectVersionNotFound) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *ListPerformanceIndicatorHistoryOfProjectVersionNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListPerformanceIndicatorHistoryOfProjectVersionConflict creates a ListPerformanceIndicatorHistoryOfProjectVersionConflict with default headers values
func NewListPerformanceIndicatorHistoryOfProjectVersionConflict() *ListPerformanceIndicatorHistoryOfProjectVersionConflict {
	return &ListPerformanceIndicatorHistoryOfProjectVersionConflict{}
}

/*ListPerformanceIndicatorHistoryOfProjectVersionConflict handles this case with default header values.

Conflict
*/
type ListPerformanceIndicatorHistoryOfProjectVersionConflict struct {
	Payload *models.APIResult
}

func (o *ListPerformanceIndicatorHistoryOfProjectVersionConflict) Error() string {
	return fmt.Sprintf("[GET /projectVersions/{parentId}/performanceIndicatorHistories][%d] listPerformanceIndicatorHistoryOfProjectVersionConflict  %+v", 409, o.Payload)
}

func (o *ListPerformanceIndicatorHistoryOfProjectVersionConflict) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *ListPerformanceIndicatorHistoryOfProjectVersionConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListPerformanceIndicatorHistoryOfProjectVersionInternalServerError creates a ListPerformanceIndicatorHistoryOfProjectVersionInternalServerError with default headers values
func NewListPerformanceIndicatorHistoryOfProjectVersionInternalServerError() *ListPerformanceIndicatorHistoryOfProjectVersionInternalServerError {
	return &ListPerformanceIndicatorHistoryOfProjectVersionInternalServerError{}
}

/*ListPerformanceIndicatorHistoryOfProjectVersionInternalServerError handles this case with default header values.

Internal Server Error
*/
type ListPerformanceIndicatorHistoryOfProjectVersionInternalServerError struct {
	Payload *models.APIResult
}

func (o *ListPerformanceIndicatorHistoryOfProjectVersionInternalServerError) Error() string {
	return fmt.Sprintf("[GET /projectVersions/{parentId}/performanceIndicatorHistories][%d] listPerformanceIndicatorHistoryOfProjectVersionInternalServerError  %+v", 500, o.Payload)
}

func (o *ListPerformanceIndicatorHistoryOfProjectVersionInternalServerError) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *ListPerformanceIndicatorHistoryOfProjectVersionInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
