// Code generated by go-swagger; DO NOT EDIT.

package issue_assignment_of_project_version_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new issue assignment of project version controller API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for issue assignment of project version controller API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	ListIssueAssignmentOfProjectVersion(params *ListIssueAssignmentOfProjectVersionParams, authInfo runtime.ClientAuthInfoWriter) (*ListIssueAssignmentOfProjectVersionOK, error)

	ReadIssueAssignmentOfProjectVersion(params *ReadIssueAssignmentOfProjectVersionParams, authInfo runtime.ClientAuthInfoWriter) (*ReadIssueAssignmentOfProjectVersionOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  ListIssueAssignmentOfProjectVersion lists
*/
func (a *Client) ListIssueAssignmentOfProjectVersion(params *ListIssueAssignmentOfProjectVersionParams, authInfo runtime.ClientAuthInfoWriter) (*ListIssueAssignmentOfProjectVersionOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListIssueAssignmentOfProjectVersionParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "listIssueAssignmentOfProjectVersion",
		Method:             "GET",
		PathPattern:        "/projectVersions/{parentId}/issueAssignment",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ListIssueAssignmentOfProjectVersionReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ListIssueAssignmentOfProjectVersionOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for listIssueAssignmentOfProjectVersion: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  ReadIssueAssignmentOfProjectVersion reads
*/
func (a *Client) ReadIssueAssignmentOfProjectVersion(params *ReadIssueAssignmentOfProjectVersionParams, authInfo runtime.ClientAuthInfoWriter) (*ReadIssueAssignmentOfProjectVersionOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewReadIssueAssignmentOfProjectVersionParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "readIssueAssignmentOfProjectVersion",
		Method:             "GET",
		PathPattern:        "/projectVersions/{parentId}/issueAssignment/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ReadIssueAssignmentOfProjectVersionReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ReadIssueAssignmentOfProjectVersionOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for readIssueAssignmentOfProjectVersion: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
