// Code generated by go-swagger; DO NOT EDIT.

package report_library_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewUploadReportLibraryParams creates a new UploadReportLibraryParams object
// with the default values initialized.
func NewUploadReportLibraryParams() *UploadReportLibraryParams {
	var ()
	return &UploadReportLibraryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUploadReportLibraryParamsWithTimeout creates a new UploadReportLibraryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUploadReportLibraryParamsWithTimeout(timeout time.Duration) *UploadReportLibraryParams {
	var ()
	return &UploadReportLibraryParams{

		timeout: timeout,
	}
}

// NewUploadReportLibraryParamsWithContext creates a new UploadReportLibraryParams object
// with the default values initialized, and the ability to set a context for a request
func NewUploadReportLibraryParamsWithContext(ctx context.Context) *UploadReportLibraryParams {
	var ()
	return &UploadReportLibraryParams{

		Context: ctx,
	}
}

// NewUploadReportLibraryParamsWithHTTPClient creates a new UploadReportLibraryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUploadReportLibraryParamsWithHTTPClient(client *http.Client) *UploadReportLibraryParams {
	var ()
	return &UploadReportLibraryParams{
		HTTPClient: client,
	}
}

/*UploadReportLibraryParams contains all the parameters to send to the API endpoint
for the upload report library operation typically these are written to a http.Request
*/
type UploadReportLibraryParams struct {

	/*Description
	  description

	*/
	Description *string
	/*File
	  file

	*/
	File runtime.NamedReadCloser

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the upload report library params
func (o *UploadReportLibraryParams) WithTimeout(timeout time.Duration) *UploadReportLibraryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the upload report library params
func (o *UploadReportLibraryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the upload report library params
func (o *UploadReportLibraryParams) WithContext(ctx context.Context) *UploadReportLibraryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the upload report library params
func (o *UploadReportLibraryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the upload report library params
func (o *UploadReportLibraryParams) WithHTTPClient(client *http.Client) *UploadReportLibraryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the upload report library params
func (o *UploadReportLibraryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDescription adds the description to the upload report library params
func (o *UploadReportLibraryParams) WithDescription(description *string) *UploadReportLibraryParams {
	o.SetDescription(description)
	return o
}

// SetDescription adds the description to the upload report library params
func (o *UploadReportLibraryParams) SetDescription(description *string) {
	o.Description = description
}

// WithFile adds the file to the upload report library params
func (o *UploadReportLibraryParams) WithFile(file runtime.NamedReadCloser) *UploadReportLibraryParams {
	o.SetFile(file)
	return o
}

// SetFile adds the file to the upload report library params
func (o *UploadReportLibraryParams) SetFile(file runtime.NamedReadCloser) {
	o.File = file
}

// WriteToRequest writes these params to a swagger request
func (o *UploadReportLibraryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Description != nil {

		// query param description
		var qrDescription string
		if o.Description != nil {
			qrDescription = *o.Description
		}
		qDescription := qrDescription
		if qDescription != "" {
			if err := r.SetQueryParam("description", qDescription); err != nil {
				return err
			}
		}

	}

	// form file param file
	if err := r.SetFileParam("file", o.File); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
