// Code generated by go-swagger; DO NOT EDIT.

package application_state_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/piper-validation/fortify-client-go/models"
)

// GetApplicationStateReader is a Reader for the GetApplicationState structure.
type GetApplicationStateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetApplicationStateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetApplicationStateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetApplicationStateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetApplicationStateUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetApplicationStateForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetApplicationStateNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewGetApplicationStateConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetApplicationStateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetApplicationStateOK creates a GetApplicationStateOK with default headers values
func NewGetApplicationStateOK() *GetApplicationStateOK {
	return &GetApplicationStateOK{}
}

/*GetApplicationStateOK handles this case with default header values.

OK
*/
type GetApplicationStateOK struct {
	Payload *models.APIResultApplicationState
}

func (o *GetApplicationStateOK) Error() string {
	return fmt.Sprintf("[GET /applicationState][%d] getApplicationStateOK  %+v", 200, o.Payload)
}

func (o *GetApplicationStateOK) GetPayload() *models.APIResultApplicationState {
	return o.Payload
}

func (o *GetApplicationStateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResultApplicationState)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetApplicationStateBadRequest creates a GetApplicationStateBadRequest with default headers values
func NewGetApplicationStateBadRequest() *GetApplicationStateBadRequest {
	return &GetApplicationStateBadRequest{}
}

/*GetApplicationStateBadRequest handles this case with default header values.

Bad Request
*/
type GetApplicationStateBadRequest struct {
	Payload *models.APIResult
}

func (o *GetApplicationStateBadRequest) Error() string {
	return fmt.Sprintf("[GET /applicationState][%d] getApplicationStateBadRequest  %+v", 400, o.Payload)
}

func (o *GetApplicationStateBadRequest) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *GetApplicationStateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetApplicationStateUnauthorized creates a GetApplicationStateUnauthorized with default headers values
func NewGetApplicationStateUnauthorized() *GetApplicationStateUnauthorized {
	return &GetApplicationStateUnauthorized{}
}

/*GetApplicationStateUnauthorized handles this case with default header values.

Unauthorized
*/
type GetApplicationStateUnauthorized struct {
	Payload *models.APIResult
}

func (o *GetApplicationStateUnauthorized) Error() string {
	return fmt.Sprintf("[GET /applicationState][%d] getApplicationStateUnauthorized  %+v", 401, o.Payload)
}

func (o *GetApplicationStateUnauthorized) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *GetApplicationStateUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetApplicationStateForbidden creates a GetApplicationStateForbidden with default headers values
func NewGetApplicationStateForbidden() *GetApplicationStateForbidden {
	return &GetApplicationStateForbidden{}
}

/*GetApplicationStateForbidden handles this case with default header values.

Forbidden
*/
type GetApplicationStateForbidden struct {
	Payload *models.APIResult
}

func (o *GetApplicationStateForbidden) Error() string {
	return fmt.Sprintf("[GET /applicationState][%d] getApplicationStateForbidden  %+v", 403, o.Payload)
}

func (o *GetApplicationStateForbidden) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *GetApplicationStateForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetApplicationStateNotFound creates a GetApplicationStateNotFound with default headers values
func NewGetApplicationStateNotFound() *GetApplicationStateNotFound {
	return &GetApplicationStateNotFound{}
}

/*GetApplicationStateNotFound handles this case with default header values.

Not Found
*/
type GetApplicationStateNotFound struct {
	Payload *models.APIResult
}

func (o *GetApplicationStateNotFound) Error() string {
	return fmt.Sprintf("[GET /applicationState][%d] getApplicationStateNotFound  %+v", 404, o.Payload)
}

func (o *GetApplicationStateNotFound) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *GetApplicationStateNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetApplicationStateConflict creates a GetApplicationStateConflict with default headers values
func NewGetApplicationStateConflict() *GetApplicationStateConflict {
	return &GetApplicationStateConflict{}
}

/*GetApplicationStateConflict handles this case with default header values.

Conflict
*/
type GetApplicationStateConflict struct {
	Payload *models.APIResult
}

func (o *GetApplicationStateConflict) Error() string {
	return fmt.Sprintf("[GET /applicationState][%d] getApplicationStateConflict  %+v", 409, o.Payload)
}

func (o *GetApplicationStateConflict) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *GetApplicationStateConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetApplicationStateInternalServerError creates a GetApplicationStateInternalServerError with default headers values
func NewGetApplicationStateInternalServerError() *GetApplicationStateInternalServerError {
	return &GetApplicationStateInternalServerError{}
}

/*GetApplicationStateInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetApplicationStateInternalServerError struct {
	Payload *models.APIResult
}

func (o *GetApplicationStateInternalServerError) Error() string {
	return fmt.Sprintf("[GET /applicationState][%d] getApplicationStateInternalServerError  %+v", 500, o.Payload)
}

func (o *GetApplicationStateInternalServerError) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *GetApplicationStateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
