// Code generated by go-swagger; DO NOT EDIT.

package alert_definition_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewReadAlertDefinitionParams creates a new ReadAlertDefinitionParams object
// with the default values initialized.
func NewReadAlertDefinitionParams() *ReadAlertDefinitionParams {
	var ()
	return &ReadAlertDefinitionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewReadAlertDefinitionParamsWithTimeout creates a new ReadAlertDefinitionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewReadAlertDefinitionParamsWithTimeout(timeout time.Duration) *ReadAlertDefinitionParams {
	var ()
	return &ReadAlertDefinitionParams{

		timeout: timeout,
	}
}

// NewReadAlertDefinitionParamsWithContext creates a new ReadAlertDefinitionParams object
// with the default values initialized, and the ability to set a context for a request
func NewReadAlertDefinitionParamsWithContext(ctx context.Context) *ReadAlertDefinitionParams {
	var ()
	return &ReadAlertDefinitionParams{

		Context: ctx,
	}
}

// NewReadAlertDefinitionParamsWithHTTPClient creates a new ReadAlertDefinitionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewReadAlertDefinitionParamsWithHTTPClient(client *http.Client) *ReadAlertDefinitionParams {
	var ()
	return &ReadAlertDefinitionParams{
		HTTPClient: client,
	}
}

/*ReadAlertDefinitionParams contains all the parameters to send to the API endpoint
for the read alert definition operation typically these are written to a http.Request
*/
type ReadAlertDefinitionParams struct {

	/*Fields
	  Output fields

	*/
	Fields *string
	/*ID
	  id

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the read alert definition params
func (o *ReadAlertDefinitionParams) WithTimeout(timeout time.Duration) *ReadAlertDefinitionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the read alert definition params
func (o *ReadAlertDefinitionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the read alert definition params
func (o *ReadAlertDefinitionParams) WithContext(ctx context.Context) *ReadAlertDefinitionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the read alert definition params
func (o *ReadAlertDefinitionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the read alert definition params
func (o *ReadAlertDefinitionParams) WithHTTPClient(client *http.Client) *ReadAlertDefinitionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the read alert definition params
func (o *ReadAlertDefinitionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFields adds the fields to the read alert definition params
func (o *ReadAlertDefinitionParams) WithFields(fields *string) *ReadAlertDefinitionParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the read alert definition params
func (o *ReadAlertDefinitionParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithID adds the id to the read alert definition params
func (o *ReadAlertDefinitionParams) WithID(id int64) *ReadAlertDefinitionParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the read alert definition params
func (o *ReadAlertDefinitionParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ReadAlertDefinitionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
