// Code generated by go-swagger; DO NOT EDIT.

package bugfield_template_group_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/piper-validation/fortify-client-go/models"
)

// MultiDeleteBugfieldTemplateGroupReader is a Reader for the MultiDeleteBugfieldTemplateGroup structure.
type MultiDeleteBugfieldTemplateGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MultiDeleteBugfieldTemplateGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewMultiDeleteBugfieldTemplateGroupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewMultiDeleteBugfieldTemplateGroupBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewMultiDeleteBugfieldTemplateGroupUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewMultiDeleteBugfieldTemplateGroupForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewMultiDeleteBugfieldTemplateGroupNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewMultiDeleteBugfieldTemplateGroupConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewMultiDeleteBugfieldTemplateGroupInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewMultiDeleteBugfieldTemplateGroupOK creates a MultiDeleteBugfieldTemplateGroupOK with default headers values
func NewMultiDeleteBugfieldTemplateGroupOK() *MultiDeleteBugfieldTemplateGroupOK {
	return &MultiDeleteBugfieldTemplateGroupOK{}
}

/*MultiDeleteBugfieldTemplateGroupOK handles this case with default header values.

OK
*/
type MultiDeleteBugfieldTemplateGroupOK struct {
	Payload *models.APIResultVoid
}

func (o *MultiDeleteBugfieldTemplateGroupOK) Error() string {
	return fmt.Sprintf("[DELETE /bugfieldTemplateGroups][%d] multiDeleteBugfieldTemplateGroupOK  %+v", 200, o.Payload)
}

func (o *MultiDeleteBugfieldTemplateGroupOK) GetPayload() *models.APIResultVoid {
	return o.Payload
}

func (o *MultiDeleteBugfieldTemplateGroupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResultVoid)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMultiDeleteBugfieldTemplateGroupBadRequest creates a MultiDeleteBugfieldTemplateGroupBadRequest with default headers values
func NewMultiDeleteBugfieldTemplateGroupBadRequest() *MultiDeleteBugfieldTemplateGroupBadRequest {
	return &MultiDeleteBugfieldTemplateGroupBadRequest{}
}

/*MultiDeleteBugfieldTemplateGroupBadRequest handles this case with default header values.

Bad Request
*/
type MultiDeleteBugfieldTemplateGroupBadRequest struct {
	Payload *models.APIResult
}

func (o *MultiDeleteBugfieldTemplateGroupBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /bugfieldTemplateGroups][%d] multiDeleteBugfieldTemplateGroupBadRequest  %+v", 400, o.Payload)
}

func (o *MultiDeleteBugfieldTemplateGroupBadRequest) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *MultiDeleteBugfieldTemplateGroupBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMultiDeleteBugfieldTemplateGroupUnauthorized creates a MultiDeleteBugfieldTemplateGroupUnauthorized with default headers values
func NewMultiDeleteBugfieldTemplateGroupUnauthorized() *MultiDeleteBugfieldTemplateGroupUnauthorized {
	return &MultiDeleteBugfieldTemplateGroupUnauthorized{}
}

/*MultiDeleteBugfieldTemplateGroupUnauthorized handles this case with default header values.

Unauthorized
*/
type MultiDeleteBugfieldTemplateGroupUnauthorized struct {
	Payload *models.APIResult
}

func (o *MultiDeleteBugfieldTemplateGroupUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /bugfieldTemplateGroups][%d] multiDeleteBugfieldTemplateGroupUnauthorized  %+v", 401, o.Payload)
}

func (o *MultiDeleteBugfieldTemplateGroupUnauthorized) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *MultiDeleteBugfieldTemplateGroupUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMultiDeleteBugfieldTemplateGroupForbidden creates a MultiDeleteBugfieldTemplateGroupForbidden with default headers values
func NewMultiDeleteBugfieldTemplateGroupForbidden() *MultiDeleteBugfieldTemplateGroupForbidden {
	return &MultiDeleteBugfieldTemplateGroupForbidden{}
}

/*MultiDeleteBugfieldTemplateGroupForbidden handles this case with default header values.

Forbidden
*/
type MultiDeleteBugfieldTemplateGroupForbidden struct {
	Payload *models.APIResult
}

func (o *MultiDeleteBugfieldTemplateGroupForbidden) Error() string {
	return fmt.Sprintf("[DELETE /bugfieldTemplateGroups][%d] multiDeleteBugfieldTemplateGroupForbidden  %+v", 403, o.Payload)
}

func (o *MultiDeleteBugfieldTemplateGroupForbidden) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *MultiDeleteBugfieldTemplateGroupForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMultiDeleteBugfieldTemplateGroupNotFound creates a MultiDeleteBugfieldTemplateGroupNotFound with default headers values
func NewMultiDeleteBugfieldTemplateGroupNotFound() *MultiDeleteBugfieldTemplateGroupNotFound {
	return &MultiDeleteBugfieldTemplateGroupNotFound{}
}

/*MultiDeleteBugfieldTemplateGroupNotFound handles this case with default header values.

Not Found
*/
type MultiDeleteBugfieldTemplateGroupNotFound struct {
	Payload *models.APIResult
}

func (o *MultiDeleteBugfieldTemplateGroupNotFound) Error() string {
	return fmt.Sprintf("[DELETE /bugfieldTemplateGroups][%d] multiDeleteBugfieldTemplateGroupNotFound  %+v", 404, o.Payload)
}

func (o *MultiDeleteBugfieldTemplateGroupNotFound) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *MultiDeleteBugfieldTemplateGroupNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMultiDeleteBugfieldTemplateGroupConflict creates a MultiDeleteBugfieldTemplateGroupConflict with default headers values
func NewMultiDeleteBugfieldTemplateGroupConflict() *MultiDeleteBugfieldTemplateGroupConflict {
	return &MultiDeleteBugfieldTemplateGroupConflict{}
}

/*MultiDeleteBugfieldTemplateGroupConflict handles this case with default header values.

Conflict
*/
type MultiDeleteBugfieldTemplateGroupConflict struct {
	Payload *models.APIResult
}

func (o *MultiDeleteBugfieldTemplateGroupConflict) Error() string {
	return fmt.Sprintf("[DELETE /bugfieldTemplateGroups][%d] multiDeleteBugfieldTemplateGroupConflict  %+v", 409, o.Payload)
}

func (o *MultiDeleteBugfieldTemplateGroupConflict) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *MultiDeleteBugfieldTemplateGroupConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMultiDeleteBugfieldTemplateGroupInternalServerError creates a MultiDeleteBugfieldTemplateGroupInternalServerError with default headers values
func NewMultiDeleteBugfieldTemplateGroupInternalServerError() *MultiDeleteBugfieldTemplateGroupInternalServerError {
	return &MultiDeleteBugfieldTemplateGroupInternalServerError{}
}

/*MultiDeleteBugfieldTemplateGroupInternalServerError handles this case with default header values.

Internal Server Error
*/
type MultiDeleteBugfieldTemplateGroupInternalServerError struct {
	Payload *models.APIResult
}

func (o *MultiDeleteBugfieldTemplateGroupInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /bugfieldTemplateGroups][%d] multiDeleteBugfieldTemplateGroupInternalServerError  %+v", 500, o.Payload)
}

func (o *MultiDeleteBugfieldTemplateGroupInternalServerError) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *MultiDeleteBugfieldTemplateGroupInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
