// Code generated by go-swagger; DO NOT EDIT.

package bugfield_template_group_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/piper-validation/fortify-client-go/models"
)

// UpdateBugfieldTemplateGroupReader is a Reader for the UpdateBugfieldTemplateGroup structure.
type UpdateBugfieldTemplateGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateBugfieldTemplateGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateBugfieldTemplateGroupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateBugfieldTemplateGroupBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewUpdateBugfieldTemplateGroupUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewUpdateBugfieldTemplateGroupForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUpdateBugfieldTemplateGroupNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewUpdateBugfieldTemplateGroupConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewUpdateBugfieldTemplateGroupInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateBugfieldTemplateGroupOK creates a UpdateBugfieldTemplateGroupOK with default headers values
func NewUpdateBugfieldTemplateGroupOK() *UpdateBugfieldTemplateGroupOK {
	return &UpdateBugfieldTemplateGroupOK{}
}

/*UpdateBugfieldTemplateGroupOK handles this case with default header values.

OK
*/
type UpdateBugfieldTemplateGroupOK struct {
	Payload *models.APIResultBugfieldTemplateGroupDto
}

func (o *UpdateBugfieldTemplateGroupOK) Error() string {
	return fmt.Sprintf("[PUT /bugfieldTemplateGroups/{id}][%d] updateBugfieldTemplateGroupOK  %+v", 200, o.Payload)
}

func (o *UpdateBugfieldTemplateGroupOK) GetPayload() *models.APIResultBugfieldTemplateGroupDto {
	return o.Payload
}

func (o *UpdateBugfieldTemplateGroupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResultBugfieldTemplateGroupDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateBugfieldTemplateGroupBadRequest creates a UpdateBugfieldTemplateGroupBadRequest with default headers values
func NewUpdateBugfieldTemplateGroupBadRequest() *UpdateBugfieldTemplateGroupBadRequest {
	return &UpdateBugfieldTemplateGroupBadRequest{}
}

/*UpdateBugfieldTemplateGroupBadRequest handles this case with default header values.

Bad Request
*/
type UpdateBugfieldTemplateGroupBadRequest struct {
	Payload *models.APIResult
}

func (o *UpdateBugfieldTemplateGroupBadRequest) Error() string {
	return fmt.Sprintf("[PUT /bugfieldTemplateGroups/{id}][%d] updateBugfieldTemplateGroupBadRequest  %+v", 400, o.Payload)
}

func (o *UpdateBugfieldTemplateGroupBadRequest) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *UpdateBugfieldTemplateGroupBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateBugfieldTemplateGroupUnauthorized creates a UpdateBugfieldTemplateGroupUnauthorized with default headers values
func NewUpdateBugfieldTemplateGroupUnauthorized() *UpdateBugfieldTemplateGroupUnauthorized {
	return &UpdateBugfieldTemplateGroupUnauthorized{}
}

/*UpdateBugfieldTemplateGroupUnauthorized handles this case with default header values.

Unauthorized
*/
type UpdateBugfieldTemplateGroupUnauthorized struct {
	Payload *models.APIResult
}

func (o *UpdateBugfieldTemplateGroupUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /bugfieldTemplateGroups/{id}][%d] updateBugfieldTemplateGroupUnauthorized  %+v", 401, o.Payload)
}

func (o *UpdateBugfieldTemplateGroupUnauthorized) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *UpdateBugfieldTemplateGroupUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateBugfieldTemplateGroupForbidden creates a UpdateBugfieldTemplateGroupForbidden with default headers values
func NewUpdateBugfieldTemplateGroupForbidden() *UpdateBugfieldTemplateGroupForbidden {
	return &UpdateBugfieldTemplateGroupForbidden{}
}

/*UpdateBugfieldTemplateGroupForbidden handles this case with default header values.

Forbidden
*/
type UpdateBugfieldTemplateGroupForbidden struct {
	Payload *models.APIResult
}

func (o *UpdateBugfieldTemplateGroupForbidden) Error() string {
	return fmt.Sprintf("[PUT /bugfieldTemplateGroups/{id}][%d] updateBugfieldTemplateGroupForbidden  %+v", 403, o.Payload)
}

func (o *UpdateBugfieldTemplateGroupForbidden) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *UpdateBugfieldTemplateGroupForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateBugfieldTemplateGroupNotFound creates a UpdateBugfieldTemplateGroupNotFound with default headers values
func NewUpdateBugfieldTemplateGroupNotFound() *UpdateBugfieldTemplateGroupNotFound {
	return &UpdateBugfieldTemplateGroupNotFound{}
}

/*UpdateBugfieldTemplateGroupNotFound handles this case with default header values.

Not Found
*/
type UpdateBugfieldTemplateGroupNotFound struct {
	Payload *models.APIResult
}

func (o *UpdateBugfieldTemplateGroupNotFound) Error() string {
	return fmt.Sprintf("[PUT /bugfieldTemplateGroups/{id}][%d] updateBugfieldTemplateGroupNotFound  %+v", 404, o.Payload)
}

func (o *UpdateBugfieldTemplateGroupNotFound) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *UpdateBugfieldTemplateGroupNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateBugfieldTemplateGroupConflict creates a UpdateBugfieldTemplateGroupConflict with default headers values
func NewUpdateBugfieldTemplateGroupConflict() *UpdateBugfieldTemplateGroupConflict {
	return &UpdateBugfieldTemplateGroupConflict{}
}

/*UpdateBugfieldTemplateGroupConflict handles this case with default header values.

Conflict
*/
type UpdateBugfieldTemplateGroupConflict struct {
	Payload *models.APIResult
}

func (o *UpdateBugfieldTemplateGroupConflict) Error() string {
	return fmt.Sprintf("[PUT /bugfieldTemplateGroups/{id}][%d] updateBugfieldTemplateGroupConflict  %+v", 409, o.Payload)
}

func (o *UpdateBugfieldTemplateGroupConflict) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *UpdateBugfieldTemplateGroupConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateBugfieldTemplateGroupInternalServerError creates a UpdateBugfieldTemplateGroupInternalServerError with default headers values
func NewUpdateBugfieldTemplateGroupInternalServerError() *UpdateBugfieldTemplateGroupInternalServerError {
	return &UpdateBugfieldTemplateGroupInternalServerError{}
}

/*UpdateBugfieldTemplateGroupInternalServerError handles this case with default header values.

Internal Server Error
*/
type UpdateBugfieldTemplateGroupInternalServerError struct {
	Payload *models.APIResult
}

func (o *UpdateBugfieldTemplateGroupInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /bugfieldTemplateGroups/{id}][%d] updateBugfieldTemplateGroupInternalServerError  %+v", 500, o.Payload)
}

func (o *UpdateBugfieldTemplateGroupInternalServerError) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *UpdateBugfieldTemplateGroupInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
