// Code generated by go-swagger; DO NOT EDIT.

package bug_filing_requirements_of_project_version_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/piper-validation/fortify-client-go/models"
)

// LoginBugFilingRequirementsOfProjectVersionReader is a Reader for the LoginBugFilingRequirementsOfProjectVersion structure.
type LoginBugFilingRequirementsOfProjectVersionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LoginBugFilingRequirementsOfProjectVersionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLoginBugFilingRequirementsOfProjectVersionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewLoginBugFilingRequirementsOfProjectVersionBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewLoginBugFilingRequirementsOfProjectVersionUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewLoginBugFilingRequirementsOfProjectVersionForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewLoginBugFilingRequirementsOfProjectVersionNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewLoginBugFilingRequirementsOfProjectVersionConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewLoginBugFilingRequirementsOfProjectVersionInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewLoginBugFilingRequirementsOfProjectVersionOK creates a LoginBugFilingRequirementsOfProjectVersionOK with default headers values
func NewLoginBugFilingRequirementsOfProjectVersionOK() *LoginBugFilingRequirementsOfProjectVersionOK {
	return &LoginBugFilingRequirementsOfProjectVersionOK{}
}

/*LoginBugFilingRequirementsOfProjectVersionOK handles this case with default header values.

OK
*/
type LoginBugFilingRequirementsOfProjectVersionOK struct {
	Payload *models.APIResultBugFilingRequirementsResponse
}

func (o *LoginBugFilingRequirementsOfProjectVersionOK) Error() string {
	return fmt.Sprintf("[POST /projectVersions/{parentId}/bugfilingrequirements/action/login][%d] loginBugFilingRequirementsOfProjectVersionOK  %+v", 200, o.Payload)
}

func (o *LoginBugFilingRequirementsOfProjectVersionOK) GetPayload() *models.APIResultBugFilingRequirementsResponse {
	return o.Payload
}

func (o *LoginBugFilingRequirementsOfProjectVersionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResultBugFilingRequirementsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewLoginBugFilingRequirementsOfProjectVersionBadRequest creates a LoginBugFilingRequirementsOfProjectVersionBadRequest with default headers values
func NewLoginBugFilingRequirementsOfProjectVersionBadRequest() *LoginBugFilingRequirementsOfProjectVersionBadRequest {
	return &LoginBugFilingRequirementsOfProjectVersionBadRequest{}
}

/*LoginBugFilingRequirementsOfProjectVersionBadRequest handles this case with default header values.

Bad Request
*/
type LoginBugFilingRequirementsOfProjectVersionBadRequest struct {
	Payload *models.APIResult
}

func (o *LoginBugFilingRequirementsOfProjectVersionBadRequest) Error() string {
	return fmt.Sprintf("[POST /projectVersions/{parentId}/bugfilingrequirements/action/login][%d] loginBugFilingRequirementsOfProjectVersionBadRequest  %+v", 400, o.Payload)
}

func (o *LoginBugFilingRequirementsOfProjectVersionBadRequest) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *LoginBugFilingRequirementsOfProjectVersionBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewLoginBugFilingRequirementsOfProjectVersionUnauthorized creates a LoginBugFilingRequirementsOfProjectVersionUnauthorized with default headers values
func NewLoginBugFilingRequirementsOfProjectVersionUnauthorized() *LoginBugFilingRequirementsOfProjectVersionUnauthorized {
	return &LoginBugFilingRequirementsOfProjectVersionUnauthorized{}
}

/*LoginBugFilingRequirementsOfProjectVersionUnauthorized handles this case with default header values.

Unauthorized
*/
type LoginBugFilingRequirementsOfProjectVersionUnauthorized struct {
	Payload *models.APIResult
}

func (o *LoginBugFilingRequirementsOfProjectVersionUnauthorized) Error() string {
	return fmt.Sprintf("[POST /projectVersions/{parentId}/bugfilingrequirements/action/login][%d] loginBugFilingRequirementsOfProjectVersionUnauthorized  %+v", 401, o.Payload)
}

func (o *LoginBugFilingRequirementsOfProjectVersionUnauthorized) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *LoginBugFilingRequirementsOfProjectVersionUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewLoginBugFilingRequirementsOfProjectVersionForbidden creates a LoginBugFilingRequirementsOfProjectVersionForbidden with default headers values
func NewLoginBugFilingRequirementsOfProjectVersionForbidden() *LoginBugFilingRequirementsOfProjectVersionForbidden {
	return &LoginBugFilingRequirementsOfProjectVersionForbidden{}
}

/*LoginBugFilingRequirementsOfProjectVersionForbidden handles this case with default header values.

Forbidden
*/
type LoginBugFilingRequirementsOfProjectVersionForbidden struct {
	Payload *models.APIResult
}

func (o *LoginBugFilingRequirementsOfProjectVersionForbidden) Error() string {
	return fmt.Sprintf("[POST /projectVersions/{parentId}/bugfilingrequirements/action/login][%d] loginBugFilingRequirementsOfProjectVersionForbidden  %+v", 403, o.Payload)
}

func (o *LoginBugFilingRequirementsOfProjectVersionForbidden) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *LoginBugFilingRequirementsOfProjectVersionForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewLoginBugFilingRequirementsOfProjectVersionNotFound creates a LoginBugFilingRequirementsOfProjectVersionNotFound with default headers values
func NewLoginBugFilingRequirementsOfProjectVersionNotFound() *LoginBugFilingRequirementsOfProjectVersionNotFound {
	return &LoginBugFilingRequirementsOfProjectVersionNotFound{}
}

/*LoginBugFilingRequirementsOfProjectVersionNotFound handles this case with default header values.

Not Found
*/
type LoginBugFilingRequirementsOfProjectVersionNotFound struct {
	Payload *models.APIResult
}

func (o *LoginBugFilingRequirementsOfProjectVersionNotFound) Error() string {
	return fmt.Sprintf("[POST /projectVersions/{parentId}/bugfilingrequirements/action/login][%d] loginBugFilingRequirementsOfProjectVersionNotFound  %+v", 404, o.Payload)
}

func (o *LoginBugFilingRequirementsOfProjectVersionNotFound) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *LoginBugFilingRequirementsOfProjectVersionNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewLoginBugFilingRequirementsOfProjectVersionConflict creates a LoginBugFilingRequirementsOfProjectVersionConflict with default headers values
func NewLoginBugFilingRequirementsOfProjectVersionConflict() *LoginBugFilingRequirementsOfProjectVersionConflict {
	return &LoginBugFilingRequirementsOfProjectVersionConflict{}
}

/*LoginBugFilingRequirementsOfProjectVersionConflict handles this case with default header values.

Conflict
*/
type LoginBugFilingRequirementsOfProjectVersionConflict struct {
	Payload *models.APIResult
}

func (o *LoginBugFilingRequirementsOfProjectVersionConflict) Error() string {
	return fmt.Sprintf("[POST /projectVersions/{parentId}/bugfilingrequirements/action/login][%d] loginBugFilingRequirementsOfProjectVersionConflict  %+v", 409, o.Payload)
}

func (o *LoginBugFilingRequirementsOfProjectVersionConflict) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *LoginBugFilingRequirementsOfProjectVersionConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewLoginBugFilingRequirementsOfProjectVersionInternalServerError creates a LoginBugFilingRequirementsOfProjectVersionInternalServerError with default headers values
func NewLoginBugFilingRequirementsOfProjectVersionInternalServerError() *LoginBugFilingRequirementsOfProjectVersionInternalServerError {
	return &LoginBugFilingRequirementsOfProjectVersionInternalServerError{}
}

/*LoginBugFilingRequirementsOfProjectVersionInternalServerError handles this case with default header values.

Internal Server Error
*/
type LoginBugFilingRequirementsOfProjectVersionInternalServerError struct {
	Payload *models.APIResult
}

func (o *LoginBugFilingRequirementsOfProjectVersionInternalServerError) Error() string {
	return fmt.Sprintf("[POST /projectVersions/{parentId}/bugfilingrequirements/action/login][%d] loginBugFilingRequirementsOfProjectVersionInternalServerError  %+v", 500, o.Payload)
}

func (o *LoginBugFilingRequirementsOfProjectVersionInternalServerError) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *LoginBugFilingRequirementsOfProjectVersionInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
