// Code generated by go-swagger; DO NOT EDIT.

package issue_summary_of_project_version_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/piper-validation/fortify-client-go/models"
)

// ListIssueSummaryOfProjectVersionReader is a Reader for the ListIssueSummaryOfProjectVersion structure.
type ListIssueSummaryOfProjectVersionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListIssueSummaryOfProjectVersionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListIssueSummaryOfProjectVersionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListIssueSummaryOfProjectVersionBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewListIssueSummaryOfProjectVersionUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewListIssueSummaryOfProjectVersionForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewListIssueSummaryOfProjectVersionNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewListIssueSummaryOfProjectVersionConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewListIssueSummaryOfProjectVersionInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListIssueSummaryOfProjectVersionOK creates a ListIssueSummaryOfProjectVersionOK with default headers values
func NewListIssueSummaryOfProjectVersionOK() *ListIssueSummaryOfProjectVersionOK {
	return &ListIssueSummaryOfProjectVersionOK{}
}

/*ListIssueSummaryOfProjectVersionOK handles this case with default header values.

OK
*/
type ListIssueSummaryOfProjectVersionOK struct {
	Payload *models.APIResultListIssueSummary
}

func (o *ListIssueSummaryOfProjectVersionOK) Error() string {
	return fmt.Sprintf("[GET /projectVersions/{parentId}/issueSummaries][%d] listIssueSummaryOfProjectVersionOK  %+v", 200, o.Payload)
}

func (o *ListIssueSummaryOfProjectVersionOK) GetPayload() *models.APIResultListIssueSummary {
	return o.Payload
}

func (o *ListIssueSummaryOfProjectVersionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResultListIssueSummary)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListIssueSummaryOfProjectVersionBadRequest creates a ListIssueSummaryOfProjectVersionBadRequest with default headers values
func NewListIssueSummaryOfProjectVersionBadRequest() *ListIssueSummaryOfProjectVersionBadRequest {
	return &ListIssueSummaryOfProjectVersionBadRequest{}
}

/*ListIssueSummaryOfProjectVersionBadRequest handles this case with default header values.

Bad Request
*/
type ListIssueSummaryOfProjectVersionBadRequest struct {
	Payload *models.APIResult
}

func (o *ListIssueSummaryOfProjectVersionBadRequest) Error() string {
	return fmt.Sprintf("[GET /projectVersions/{parentId}/issueSummaries][%d] listIssueSummaryOfProjectVersionBadRequest  %+v", 400, o.Payload)
}

func (o *ListIssueSummaryOfProjectVersionBadRequest) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *ListIssueSummaryOfProjectVersionBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListIssueSummaryOfProjectVersionUnauthorized creates a ListIssueSummaryOfProjectVersionUnauthorized with default headers values
func NewListIssueSummaryOfProjectVersionUnauthorized() *ListIssueSummaryOfProjectVersionUnauthorized {
	return &ListIssueSummaryOfProjectVersionUnauthorized{}
}

/*ListIssueSummaryOfProjectVersionUnauthorized handles this case with default header values.

Unauthorized
*/
type ListIssueSummaryOfProjectVersionUnauthorized struct {
	Payload *models.APIResult
}

func (o *ListIssueSummaryOfProjectVersionUnauthorized) Error() string {
	return fmt.Sprintf("[GET /projectVersions/{parentId}/issueSummaries][%d] listIssueSummaryOfProjectVersionUnauthorized  %+v", 401, o.Payload)
}

func (o *ListIssueSummaryOfProjectVersionUnauthorized) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *ListIssueSummaryOfProjectVersionUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListIssueSummaryOfProjectVersionForbidden creates a ListIssueSummaryOfProjectVersionForbidden with default headers values
func NewListIssueSummaryOfProjectVersionForbidden() *ListIssueSummaryOfProjectVersionForbidden {
	return &ListIssueSummaryOfProjectVersionForbidden{}
}

/*ListIssueSummaryOfProjectVersionForbidden handles this case with default header values.

Forbidden
*/
type ListIssueSummaryOfProjectVersionForbidden struct {
	Payload *models.APIResult
}

func (o *ListIssueSummaryOfProjectVersionForbidden) Error() string {
	return fmt.Sprintf("[GET /projectVersions/{parentId}/issueSummaries][%d] listIssueSummaryOfProjectVersionForbidden  %+v", 403, o.Payload)
}

func (o *ListIssueSummaryOfProjectVersionForbidden) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *ListIssueSummaryOfProjectVersionForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListIssueSummaryOfProjectVersionNotFound creates a ListIssueSummaryOfProjectVersionNotFound with default headers values
func NewListIssueSummaryOfProjectVersionNotFound() *ListIssueSummaryOfProjectVersionNotFound {
	return &ListIssueSummaryOfProjectVersionNotFound{}
}

/*ListIssueSummaryOfProjectVersionNotFound handles this case with default header values.

Not Found
*/
type ListIssueSummaryOfProjectVersionNotFound struct {
	Payload *models.APIResult
}

func (o *ListIssueSummaryOfProjectVersionNotFound) Error() string {
	return fmt.Sprintf("[GET /projectVersions/{parentId}/issueSummaries][%d] listIssueSummaryOfProjectVersionNotFound  %+v", 404, o.Payload)
}

func (o *ListIssueSummaryOfProjectVersionNotFound) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *ListIssueSummaryOfProjectVersionNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListIssueSummaryOfProjectVersionConflict creates a ListIssueSummaryOfProjectVersionConflict with default headers values
func NewListIssueSummaryOfProjectVersionConflict() *ListIssueSummaryOfProjectVersionConflict {
	return &ListIssueSummaryOfProjectVersionConflict{}
}

/*ListIssueSummaryOfProjectVersionConflict handles this case with default header values.

Conflict
*/
type ListIssueSummaryOfProjectVersionConflict struct {
	Payload *models.APIResult
}

func (o *ListIssueSummaryOfProjectVersionConflict) Error() string {
	return fmt.Sprintf("[GET /projectVersions/{parentId}/issueSummaries][%d] listIssueSummaryOfProjectVersionConflict  %+v", 409, o.Payload)
}

func (o *ListIssueSummaryOfProjectVersionConflict) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *ListIssueSummaryOfProjectVersionConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListIssueSummaryOfProjectVersionInternalServerError creates a ListIssueSummaryOfProjectVersionInternalServerError with default headers values
func NewListIssueSummaryOfProjectVersionInternalServerError() *ListIssueSummaryOfProjectVersionInternalServerError {
	return &ListIssueSummaryOfProjectVersionInternalServerError{}
}

/*ListIssueSummaryOfProjectVersionInternalServerError handles this case with default header values.

Internal Server Error
*/
type ListIssueSummaryOfProjectVersionInternalServerError struct {
	Payload *models.APIResult
}

func (o *ListIssueSummaryOfProjectVersionInternalServerError) Error() string {
	return fmt.Sprintf("[GET /projectVersions/{parentId}/issueSummaries][%d] listIssueSummaryOfProjectVersionInternalServerError  %+v", 500, o.Payload)
}

func (o *ListIssueSummaryOfProjectVersionInternalServerError) GetPayload() *models.APIResult {
	return o.Payload
}

func (o *ListIssueSummaryOfProjectVersionInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
