// Code generated by go-swagger; DO NOT EDIT.

package role_of_auth_entity_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListRoleOfAuthEntityParams creates a new ListRoleOfAuthEntityParams object
// with the default values initialized.
func NewListRoleOfAuthEntityParams() *ListRoleOfAuthEntityParams {
	var ()
	return &ListRoleOfAuthEntityParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListRoleOfAuthEntityParamsWithTimeout creates a new ListRoleOfAuthEntityParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListRoleOfAuthEntityParamsWithTimeout(timeout time.Duration) *ListRoleOfAuthEntityParams {
	var ()
	return &ListRoleOfAuthEntityParams{

		timeout: timeout,
	}
}

// NewListRoleOfAuthEntityParamsWithContext creates a new ListRoleOfAuthEntityParams object
// with the default values initialized, and the ability to set a context for a request
func NewListRoleOfAuthEntityParamsWithContext(ctx context.Context) *ListRoleOfAuthEntityParams {
	var ()
	return &ListRoleOfAuthEntityParams{

		Context: ctx,
	}
}

// NewListRoleOfAuthEntityParamsWithHTTPClient creates a new ListRoleOfAuthEntityParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListRoleOfAuthEntityParamsWithHTTPClient(client *http.Client) *ListRoleOfAuthEntityParams {
	var ()
	return &ListRoleOfAuthEntityParams{
		HTTPClient: client,
	}
}

/*ListRoleOfAuthEntityParams contains all the parameters to send to the API endpoint
for the list role of auth entity operation typically these are written to a http.Request
*/
type ListRoleOfAuthEntityParams struct {

	/*Fields
	  Output fields

	*/
	Fields *string
	/*ParentID
	  parentId

	*/
	ParentID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list role of auth entity params
func (o *ListRoleOfAuthEntityParams) WithTimeout(timeout time.Duration) *ListRoleOfAuthEntityParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list role of auth entity params
func (o *ListRoleOfAuthEntityParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list role of auth entity params
func (o *ListRoleOfAuthEntityParams) WithContext(ctx context.Context) *ListRoleOfAuthEntityParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list role of auth entity params
func (o *ListRoleOfAuthEntityParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list role of auth entity params
func (o *ListRoleOfAuthEntityParams) WithHTTPClient(client *http.Client) *ListRoleOfAuthEntityParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list role of auth entity params
func (o *ListRoleOfAuthEntityParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFields adds the fields to the list role of auth entity params
func (o *ListRoleOfAuthEntityParams) WithFields(fields *string) *ListRoleOfAuthEntityParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the list role of auth entity params
func (o *ListRoleOfAuthEntityParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithParentID adds the parentID to the list role of auth entity params
func (o *ListRoleOfAuthEntityParams) WithParentID(parentID int64) *ListRoleOfAuthEntityParams {
	o.SetParentID(parentID)
	return o
}

// SetParentID adds the parentId to the list role of auth entity params
func (o *ListRoleOfAuthEntityParams) SetParentID(parentID int64) {
	o.ParentID = parentID
}

// WriteToRequest writes these params to a swagger request
func (o *ListRoleOfAuthEntityParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	// path param parentId
	if err := r.SetPathParam("parentId", swag.FormatInt64(o.ParentID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
