// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AuthTokenRevokeRequest Request for revoking tokens by value
// swagger:model AuthTokenRevokeRequest
type AuthTokenRevokeRequest struct {

	// A list of tokens (atleast one) to revoke
	// Required: true
	Tokens []string `json:"tokens"`
}

// Validate validates this auth token revoke request
func (m *AuthTokenRevokeRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTokens(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AuthTokenRevokeRequest) validateTokens(formats strfmt.Registry) error {

	if err := validate.Required("tokens", "body", m.Tokens); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AuthTokenRevokeRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AuthTokenRevokeRequest) UnmarshalBinary(b []byte) error {
	var res AuthTokenRevokeRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
