// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DynamicScanRequestParameterOption Dynamic Scan Request Parameter Option DTO object
// swagger:model DynamicScanRequestParameterOption
type DynamicScanRequestParameterOption struct {

	// description
	Description string `json:"description,omitempty"`

	// Unique string identifier for a Dynamic Scan Request Parameter Option
	GUID string `json:"guid,omitempty"`

	// Unique ID for this parameter option
	// Required: true
	ID *int64 `json:"id"`

	// Index of this option in list of options
	// Required: true
	Index *int32 `json:"index"`

	// Name
	// Required: true
	Name *string `json:"name"`
}

// Validate validates this dynamic scan request parameter option
func (m *DynamicScanRequestParameterOption) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateIndex(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DynamicScanRequestParameterOption) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *DynamicScanRequestParameterOption) validateIndex(formats strfmt.Registry) error {

	if err := validate.Required("index", "body", m.Index); err != nil {
		return err
	}

	return nil
}

func (m *DynamicScanRequestParameterOption) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DynamicScanRequestParameterOption) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DynamicScanRequestParameterOption) UnmarshalBinary(b []byte) error {
	var res DynamicScanRequestParameterOption
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
