// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PluginEnableRequest Request to enable plugin
// swagger:model PluginEnableRequest
type PluginEnableRequest struct {

	// List containing single plugin ID to enable
	// Required: true
	PluginIds []int64 `json:"pluginIds"`
}

// Validate validates this plugin enable request
func (m *PluginEnableRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePluginIds(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PluginEnableRequest) validatePluginIds(formats strfmt.Registry) error {

	if err := validate.Required("pluginIds", "body", m.PluginIds); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PluginEnableRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PluginEnableRequest) UnmarshalBinary(b []byte) error {
	var res PluginEnableRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
